// English content. Same structure as fr.mjs (the build checks it).

export default {
  lang: 'en',
  locale: 'en_GB',
  dir: 'en/',
  alternate: { lang: 'fr', dir: '', label: 'FR', name: 'Version française' },

  meta: {
    title: 'MRGMF · Fodié Marega: IAM, identity governance and architecture',
    description:
      'The playable portfolio of Fodié Marega, End User Architect at Louis Vuitton specialising in IAM: identity governance and architecture, Microsoft 365, Nexthink and cloud automation, arcade style.',
    ogAlt: 'Arcade-style title screen: MRGMF, Zero Trust Fighter.',
    notFoundTitle: 'Game over · MRGMF',
  },

  ui: {
    skip: 'Skip to content',
    nav: 'Main navigation',
    navItems: [
      { id: 'select', label: 'Projects', icon: 'grid' },
      { id: 'progress', label: 'Progress', icon: 'stairs' },
      { id: 'moves', label: 'Skills', icon: 'bolt' },
      { id: 'profile', label: 'Profile', icon: 'user' },
      { id: 'contact', label: 'Contact', icon: 'mail' },
    ],
    screens: {
      title: 'Title screen',
      select: 'Select',
      progress: 'Progress',
      moves: 'Skills',
      profile: 'Profile',
      contact: 'Contact',
      stage: 'Fight',
      upgrade: 'Upgrade',
    },
    sound: 'Sound',
    on: 'ON',
    off: 'OFF',
    readingMode: 'Reading mode',
    arcadeMode: 'Arcade mode',
    help: 'Controls',
    helpShort: 'Help',
    close: 'Close',
    back: 'Back',
    langSwitch: 'Passer en français',
    toastSoundOn: 'Sound on',
    toastSoundOff: 'Sound off',
    toastReading: 'Reading mode',
    toastArcade: 'Arcade mode',
    announceScreen: 'Screen',
    padConnected: 'Gamepad connected',
    footer: 'Handmade, no framework.',
    source: 'Source code',
    helpItems: [
      ['Arrows or WASD', 'Move, choose'],
      ['Enter or J', 'Confirm · punch (P)'],
      ['K', 'Kick (K)'],
      ['Esc', 'Back'],
      ['M', 'Toggle sound'],
      ['?', 'Show this help'],
      ['Gamepad', 'D-pad + A (confirm) / B (back)'],
    ],
    helpNote:
      'Motions (236P, 623K…) use fighting-game numpad notation: 2 = down, 6 = forward, 3 = down-forward.',
  },

  title: {
    logo: 'MRGMF',
    subtitle: 'Zero Trust Fighter',
    tagline: 'Secure the access. Automate the rest.',
    role: 'IAM · Identity governance & architecture',
    blurb:
      'The playable portfolio of Fodié Marega, End User Architect specialising in IAM: who has access to what, why, and how to prove it. Every boss is a problem to solve, every company a team, every degree an upgrade.',
    start: 'Start',
    startHint: 'or press Enter',
    credit: 'Credit 01',
    reading: 'No time to play? Reading mode',
  },

  select: {
    heading: 'Choose your mission',
    subtitle:
      'Every mission puts player 1 up against a real problem. The companies are on his team. Everything stays readable, even without fighting.',
    tip: 'Tip: arrows + Enter, or click a mission.',
    readingHeading: 'Projects and experience',
    readingIntro: 'Every mission is a fight against one specific problem, as part of a team or solo.',
    p1: 'Player 1',
    p2: 'Opponent',
    mission: 'Mission',
    hints: 'Arrows / WASD: choose · Enter or J: start the mission · Esc: back',
    random: { name: 'Random', tagline: 'Let fate pick your mission.', crew: 'Surprise' },
    locked: { name: '???', tagline: 'Secret mission. Rumour says an old code unlocks it…', boss: '?' },
    lockedToast: 'Locked. Try a famous code…',
    unlockedToast: 'New mission: ARCHIVES',
  },

  fight: {
    round: 'Round 1',
    fight: 'Fight!',
    ko: 'K.O.',
    perfect: 'Perfect',
    hits: 'hits',
    hit: 'hit',
    special: 'Special!',
    super: 'Super!',
    attack: 'Attack',
    skip: 'Skip the fight',
    replay: 'Play again',
    next: 'Next',
    toSelect: 'Back to missions',
    results: 'Results',
    stack: 'Arsenal',
    combo: 'Combo',
    highlights: 'Highlights',
    brief: 'Brief',
    tabsLabel: 'Fight content',
    backToProjects: 'All missions',
    access: 'Open the project',
    opponent: 'Opponent',
    team: 'Team',
    assist: 'Assist',
    nextLabel: 'Next step',
    controlsHint: 'Hit with J or the button. Special motions count double.',
    commentaryIdle: 'Press “Attack” to start the combo, or browse the tabs.',
    vs: 'VS',
    perksTitle: 'Skills earned',
  },

  // Select order: most recent experience first.
  stages: [
    {
      id: 'lv',
      team: 'lv',
      tile: 'End User Architect',
      name: 'End User Architect',
      kicker: 'Apprenticeship at Louis Vuitton · since 2025',
      tagline: 'Governing identities and the Microsoft 365 workplace, then automating whatever can be.',
      meta: ['Since 2025', 'Apprenticeship', 'M365 · Entra ID · Azure'],
      boss: {
        name: 'Implicit Trust',
        sprite: 'ghost',
        desc: 'Assumes an access is legitimate because it has always worked.',
      },
      intro:
        'As an apprentice in the Digital Workplace team at Louis Vuitton, I am an End User Architect: I work on the Microsoft 365 environment and identity governance. Who accesses what, under which conditions, and how it is traced, at the scale of a large organisation. Internal details stay internal.',
      hits: [
        { name: 'Microsoft 365 tenant', desc: 'Exchange Online, Teams, SharePoint: accounts, access and external collaboration.' },
        { name: 'Conditional Access', desc: 'A Microsoft Entra ID policy requiring MFA for guest accounts.' },
        { name: 'Report-only mode', desc: 'Measure the real impact of a policy before switching it on.' },
        { name: 'Ring deployment', desc: 'Gradual rollout, group by group, so nobody gets locked out.' },
        { name: 'Access request', desc: 'Group access requested self-service in Power Apps, then applied by Azure Automation.' },
        { name: 'PowerShell Barrage', desc: 'Automated monitoring report (REST API, diff against the previous run, alerts), delivered through Microsoft Graph.' },
        { name: 'Key Vault Guard', desc: 'Server-to-server OAuth 2.0, secrets kept in Azure Key Vault: never in the script.' },
        { name: 'DNS · CDN · TLS', desc: 'Event web access going live: subdomain, CDN, certificate, opening on schedule.' },
      ],
      super: {
        name: 'Zero Trust',
        desc: 'Never trust, always verify: every access is explicit, logged and verifiable.',
      },
      results: [
        { value: '3', label: 'workstreams: guest MFA, automated monitoring, event access' },
        { value: '2', label: 'shipped to production' },
        { value: '0', label: 'incidents on event access' },
      ],
      stack: ['Microsoft 365', 'Exchange Online', 'Teams', 'SharePoint', 'Microsoft Entra ID', 'Conditional Access', 'PowerShell', 'Microsoft Graph', 'Azure Key Vault', 'Azure Automation', 'Power Apps', 'Zoom API'],
      note: 'Apprenticeship work: no public code. The demo recreates the principle with generic policies.',
      access: [{ label: 'Conditional Access simulator', href: 'demos/acces-conditionnel/', kind: 'demo' }],
      perks: ['Microsoft 365', 'Conditional Access', 'Azure Automation'],
    },
    {
      id: 'nexthink',
      team: 'lv',
      assist: 'nexthink',
      tile: 'Digital experience',
      name: 'Digital experience',
      kicker: 'Apprenticeship at Louis Vuitton · since 2025',
      tagline: 'See what employees go through on their devices, and fix it before they call support.',
      meta: ['Since 2025', 'Apprenticeship', 'Nexthink · NQL · DEX'],
      boss: {
        name: 'The Drift',
        sprite: 'laptop',
        desc: 'A device quietly falls out of compliance… until it breaks.',
      },
      intro:
        'With Nexthink as backup, I monitor the digital employee experience (DEX) and fleet compliance: spot the devices that drift, warn the people affected and fix things remotely.',
      hits: [
        { name: 'NQL query', desc: 'Investigations in NQL to query the real state of the fleet.' },
        { name: 'Compliance dashboard', desc: 'Fleet compliance dashboards, shared with the teams.' },
        { name: 'Remote Action', desc: 'Diagnostic and remediation scripts pushed remotely to devices.' },
        { name: 'Campaign', desc: 'Targeted surveys and messages sent to the employees concerned.' },
        { name: 'Alert', desc: 'Incident alerts, to act before the tickets come in.' },
        { name: 'DEX score', desc: 'Tracking the digital experience score to measure the effect of each action.' },
      ],
      super: {
        name: 'Proactive remediation',
        desc: 'Detect, warn, fix: the problem is solved before anyone reports it.',
      },
      results: [
        { value: '2', label: 'Nexthink Associate certifications (2026)' },
        { value: '4', label: 'levers: queries, remote actions, campaigns, alerts' },
      ],
      stack: ['Nexthink Infinity', 'NQL', 'Remote Actions', 'Campaigns', 'Alerts', 'DEX score', 'PowerShell'],
      note: 'Apprenticeship work. The demo uses entirely fictitious data.',
      access: [{ label: 'DEX console (fictitious data)', href: 'demos/nexthink/', kind: 'demo' }],
      perks: ['Nexthink', 'NQL', 'DEX score'],
    },
    {
      id: 'learnlink',
      crew: 'Solo',
      tile: 'LearnLink',
      name: 'LearnLink',
      kicker: 'Final-year project · 2026 · solo',
      tagline: 'A secure e-learning platform: from course to verifiable certificate.',
      meta: ['2026', 'Solo', 'Node · React · MongoDB · PostgreSQL'],
      boss: {
        name: 'Brute Force',
        sprite: 'ram',
        desc: 'Keeps trying passwords until an account gives in.',
      },
      intro:
        'My final-year project: free courses and a certificate anyone can verify, without ever letting an account fall. Designed, built and tested solo, all the way to containers and monitoring.',
      hits: [
        { name: 'bcrypt ×12', desc: 'Passwords hashed with bcrypt (12 rounds): even if stolen, they stay useless.' },
        { name: 'TOTP · RFC 6238', desc: 'App-based second factor (Google Authenticator, Authy), with backup codes.' },
        { name: 'OAuth 2.0', desc: 'Sign in with Google or GitHub, no new password to remember.' },
        { name: 'Anti brute-force', desc: 'Adaptive CAPTCHA after 3 failures, temporary lockout at 10, security alert at 15.' },
        { name: 'RBAC · 5 roles', desc: 'Student, trainer, manager, curriculum lead, admin: each with its own rights, enforced server-side.' },
        { name: 'SIEM log', desc: 'Authentication events as normalised JSON, Prometheus metrics and Grafana dashboards.' },
      ],
      super: {
        name: 'Verifiable certificate',
        desc: 'QR code and public page: a recruiter checks a certificate in one scan, no account needed.',
      },
      results: [
        { value: '17', label: 'Jest tests run in CI' },
        { value: '8', label: 'Docker Compose services' },
        { value: '5', label: 'OWASP Top 10 risks covered' },
        { value: '2', label: 'blocking bugs found in QA, fixed' },
      ],
      stack: ['Node.js', 'Express 5', 'React 19', 'Vite', 'Tailwind', 'MongoDB', 'PostgreSQL', 'Redis', 'BullMQ', 'Socket.io', 'Stripe', 'Docker', 'GitHub Actions', 'Prometheus', 'Grafana', 'Jest'],
      note: 'Private code (certification file). The demo recreates the security mechanisms in the browser.',
      access: [{ label: 'Live MFA sign-in', href: 'demos/learnlink/', kind: 'demo' }],
      perks: ['Node.js', 'React', 'MFA / TOTP', 'Docker'],
    },
    {
      id: 'bain',
      team: 'bain',
      tile: 'IT support',
      name: 'IT support, up to L3',
      kicker: 'Apprenticeship at Bain & Company · 2023 – 2025',
      tagline: 'From the first ticket to level 3: two years keeping the workplace of a global firm running.',
      meta: ['2023 – 2025', 'Apprenticeship', 'ServiceNow · AD · PowerShell'],
      boss: {
        name: 'The Ticket Hydra',
        sprite: 'hydra',
        desc: 'Close one ticket, two grow back.',
      },
      intro:
        'Two years as an IT assistant apprentice at Bain & Company France. I started at level 1 and finished at level 3: from hardware diagnostics all the way to administration and automation.',
      hits: [
        { name: 'L1 · Diagnostics', desc: 'First level: hardware diagnostics and repair, direct support to users.' },
        { name: 'L1 · Fleet & stock', desc: 'Managing stock and the device fleet, preparing workstations.' },
        { name: 'L2 · ServiceNow', desc: 'Handling level 2 incidents and requests in ServiceNow.' },
        { name: 'L2 · Active Directory', desc: 'Managing accounts, groups and access rights.' },
        { name: 'L3 · Servers', desc: 'Third level: server management and the most complex incidents.' },
        { name: 'L3 · Automation', desc: 'Recurring tasks automated with PowerShell and Power Automate.' },
      ],
      super: {
        name: 'Level 3 reached',
        desc: 'From L1 to L3 in two years, alongside local and international IT teams.',
      },
      results: [
        { value: 'L3', label: 'reached in two years, starting from L1' },
        { value: '2', label: 'years of apprenticeship' },
        { value: 'FR · EN', label: 'local and international teams' },
      ],
      stack: ['ServiceNow', 'Active Directory', 'PowerShell', 'Power Automate', 'Windows', 'Microsoft 365', 'Hardware'],
      note: 'Work experience. The demo recreates support triage as a mini-game.',
      access: [{ label: 'Ticket Rush (mini-game)', href: 'demos/tickets/', kind: 'demo' }],
      perks: ['Support L1 to L3', 'Active Directory', 'ServiceNow'],
    },
    {
      id: 'hotel',
      crew: 'Pair project',
      tile: 'Hotel.java',
      name: 'Hotel.java',
      kicker: 'School pair project · 2025',
      tagline: 'Hotel management in Java: rooms, guests, bookings and services.',
      meta: ['2025', 'Duo', 'Java · OOP'],
      boss: {
        name: 'Overbooking',
        sprite: 'bell',
        desc: 'Two guests, one room, zero business rules.',
      },
      intro:
        'A school project with a teammate: model a hotel with object-oriented programming, from the room to the bill. I owned the guest booking flow and the services logic.',
      hits: [
        { name: 'Abstract class', desc: 'Room sets the contract; Single, Double and Suite refine it.' },
        { name: 'Polymorphism', desc: 'Each room type prices itself, and the Suite (jacuzzi, balcony) overrides the calculation.' },
        { name: 'java.time', desc: 'Number of nights computed from real dates, no hacks.' },
        { name: 'À la carte services', desc: 'Breakfast, spa… added to the booking and billed.' },
        { name: 'Filtered search', desc: 'Rooms by number, by type or under a maximum budget.' },
      ],
      super: {
        name: 'Final bill',
        desc: 'Room + services: the total price computes itself, booking by booking.',
      },
      results: [
        { value: '9', label: 'Java classes' },
        { value: '3', label: 'room types' },
        { value: '2', label: 'developers' },
      ],
      stack: ['Java', 'OOP', 'java.time', 'Collections', 'Eclipse', 'Git'],
      note: 'Original code is private (pair project). The demo reuses the object model and its prices.',
      access: [{ label: 'Book a room', href: 'demos/hotel/', kind: 'demo' }],
      perks: ['Java', 'OOP'],
    },
    {
      id: 'trone',
      crew: 'Team of three',
      tile: 'ProjecTTrone',
      name: 'ProjecTTrone',
      kicker: 'Team of three · 2023',
      tagline: 'A 3D action game built by three people, from Unreal Engine to Unity.',
      meta: ['2023', 'Trio', 'Unity · C# · Unreal'],
      boss: {
        name: 'The 3D Engine',
        sprite: 'cube',
        desc: 'Physics, cameras, collisions: a whole world to tame.',
      },
      intro:
        'My first big team project: a medieval 3D town to explore, with items and weapons to pick up. A V1 in Unreal Engine, then a V2 in Unity. I built the menus, the inventory and item pickup, and handled branch merges.',
      hits: [
        { name: 'V1 · Unreal Engine', desc: 'First prototype in C++ and Blueprints.' },
        { name: 'V2 · Unity 2022', desc: 'Rebuilt in C# to iterate faster.' },
        { name: 'Third-person camera', desc: 'Character controller and a camera that follows the player.' },
        { name: 'Inventory', desc: 'Items and data kept apart (Item / ItemData), panel toggled with the I key.' },
        { name: 'Item pickup', desc: 'Raycast detection: “Press E” as soon as an item is in range.' },
        { name: 'Team Git', desc: 'One branch per feature (menu, map, items), then merge.' },
      ],
      super: {
        name: 'Medieval town',
        desc: 'Character, map and items brought together in one playable scene.',
      },
      results: [
        { value: '3', label: 'developers' },
        { value: '2', label: 'game engines' },
        { value: '3', label: 'scenes (menu, town, sandbox)' },
      ],
      stack: ['Unity', 'C#', 'Unreal Engine', 'C++', 'Blueprints', 'Git'],
      note: 'Original code is private (licensed assets). The demo recreates item pickup and the inventory in 2D.',
      access: [{ label: 'ProjecTTrone Lite (mini-game)', href: 'demos/projecttrone/', kind: 'demo' }],
      perks: ['Unity', 'C#', 'Teamwork'],
    },
    {
      id: 'portfolio',
      crew: 'Solo',
      tile: 'Portfolio',
      name: 'This portfolio',
      kicker: 'Solo project · 2026',
      tagline: 'A playable portfolio, handmade, no framework.',
      meta: ['2026', 'Solo', 'HTML · CSS · JS'],
      boss: {
        name: 'The Boring Résumé',
        sprite: 'paper',
        desc: 'One page, bullet points, and nobody reads to the end.',
      },
      intro:
        'Instead of yet another résumé, an arcade cabinet: every project is a mission against a problem, every skill a motion input, every degree an upgrade. Everything is handmade and still readable without JavaScript.',
      hits: [
        { name: 'Zero framework', desc: 'Plain HTML, CSS and JavaScript, as ES modules.' },
        { name: 'Homemade build', desc: 'A dependency-free Node generator outputs the FR and EN pages.' },
        { name: 'SVG pixel art', desc: 'Sprites drawn in code, rendered as crisp SVG at any size.' },
        { name: 'Input buffer', desc: 'Fighting-game motion detection (236P, 623K…), AZERTY or QWERTY.' },
        { name: 'Gamepad', desc: 'Gamepad API: plug in your pad or arcade stick.' },
        { name: 'Security', desc: 'Strict CSP, no external resources, CI with CodeQL analysis.' },
      ],
      super: {
        name: 'Reading mode',
        desc: 'A calm, accessible version with no animation, one click away.',
      },
      results: [
        { value: '0', label: 'runtime dependencies' },
        { value: '2', label: 'languages' },
        { value: '6', label: 'playable demos, one per project' },
      ],
      stack: ['HTML', 'CSS', 'JavaScript', 'Node.js', 'SVG', 'Web Audio', 'Gamepad API', 'GitHub Actions', 'CodeQL', 'GitHub Pages'],
      note: '',
      access: [{ label: 'Source code', href: 'https://github.com/MrgMF/MRGMF.github.io', kind: 'code' }],
      perks: ['Native web', 'Accessibility', 'CSP'],
    },
    {
      id: 'archives',
      secret: true,
      crew: 'Solo',
      tile: 'Archives',
      name: 'Archives',
      kicker: 'Secret mission · 2023 – 2025',
      tagline: 'The first rounds.',
      meta: ['2023 – 2025', 'Early days', 'HTML · PHP · React'],
      boss: {
        name: 'The Floppy Disk',
        sprite: 'floppy',
        desc: 'It keeps everything. Even the first attempts.',
      },
      intro: 'Mission unlocked! Here are the earlier projects: not perfect, but that is where it all started.',
      hits: [
        { name: 'ArtisteCity · 2023', desc: 'A social network for artists: gallery, track previews, file uploads (HTML, CSS, PHP).' },
        { name: 'Tutor matching · 2025', desc: 'Interactive student / teacher mock-up: profiles, chat, settings (React, TypeScript, prototyped with Figma Make).' },
      ],
      super: {
        name: 'First website',
        desc: 'An HTML résumé on GitHub Pages. This portfolio took its place.',
      },
      results: [
        { value: '2021', label: 'first GitHub account' },
        { value: '2023', label: 'first projects online' },
      ],
      stack: ['HTML', 'CSS', 'PHP', 'React', 'TypeScript', 'Figma'],
      note: '',
      access: [],
      perks: [],
    },
  ],

  // Degrees and certifications: player 1's upgrades.
  upgrades: [
    { id: 'bac', icon: 'scroll', kind: 'Diploma', name: 'Baccalauréat STI2D', org: 'French high-school diploma in industrial science and technology', date: '2020', perks: ['Electronics', 'Systems'] },
    { id: 'licence', icon: 'scroll', kind: 'University', name: 'Bachelor’s studies in Maths & Computer Science', org: 'Université d’Évry', date: '2020 – 2022', perks: ['Mathematics', 'Algorithms'] },
    { id: 'bts', icon: 'scroll', kind: 'Diploma', name: 'BTS CIEL', org: 'Two-year degree in cybersecurity, IT and networks · apprenticeship', date: '2023 – 2025', perks: ['Networks', 'Cybersecurity'] },
    { id: 'cisco', icon: 'medal', kind: 'Certification', name: 'Junior Cybersecurity Analyst', org: 'Cisco · career path', date: 'March 2025', perks: ['Security analysis'] },
    {
      id: 'lvmh',
      icon: 'medal',
      kind: 'Certifications',
      name: 'LVMH Fast Tracks',
      org: 'LVMH · 6 certificates',
      date: 'July – August 2025',
      perks: ['Data', 'Generative AI', 'Ethics & compliance'],
      list: ['Data Fast Track', 'Cybersecurity Fast Track', 'Generative AI Fast Track', 'Green in Tech Fast Track', 'Clienteling Fast Track', 'Ethics & Compliance Certificate'],
    },
    {
      id: 'nxt',
      icon: 'medal',
      kind: 'Certifications',
      name: 'Certified Nexthink Associate',
      org: 'Nexthink · 2 certifications',
      date: 'January 2026',
      perks: ['Nexthink', 'DEX'],
      list: ['Certified Nexthink Associate', 'Certified Nexthink Associate in IT Support'],
    },
    { id: 'bachelor', icon: 'cap', kind: 'Degree', name: 'Bachelor in Application Design & Development', org: 'ECE Paris · apprenticeship', date: '2025 – 2026', perks: ['Software design', 'Layered architecture'] },
    { id: 'rncp', icon: 'medal', kind: 'Title', name: 'RNCP level 6 title obtained', org: 'Application Designer & Developer (EQF level 6)', date: '2026', perks: ['Testing & DevOps', 'Application security'] },
    { id: 'ece', icon: 'cap', kind: 'Degree in progress', name: 'Engineering degree · Data & AI', org: 'ECE Paris · apprenticeship at Louis Vuitton', date: '2026 – 2029', perks: ['Data', 'AI'], status: 'In progress' },
    { id: 'next', icon: 'lock', kind: '???', name: 'Next upgrade', org: 'To unlock', date: '…', perks: [], locked: true },
  ],

  // Companies are never opponents: they are player 1's teams.
  // Nexthink is an "assist" ally called in as backup.
  teams: {
    heading: 'Teams & allies',
    intro: 'Companies are not opponents: they are the teams I fight problems alongside.',
    team: 'Team',
    ally: 'Ally',
    missions: 'Missions',
    list: [
      {
        id: 'lv',
        kind: 'team',
        name: 'Louis Vuitton',
        role: 'End User Architect · apprenticeship',
        date: 'Since 2025',
        desc: 'Digital Workplace team: Microsoft 365, identity governance and the digital employee experience.',
      },
      {
        id: 'bain',
        kind: 'team',
        name: 'Bain & Company',
        role: 'IT assistant · apprenticeship',
        date: '2023 – 2025',
        desc: 'IT support from level 1 to level 3, alongside local and international IT teams.',
      },
      {
        id: 'nexthink',
        kind: 'ally',
        sprite: 'drone',
        name: 'Nexthink',
        role: 'Assist · DEX platform',
        date: 'Certified ×2 (2026)',
        desc: 'Watches the fleet, spots the devices that drift and fixes them remotely. Called in as backup in the Digital experience mission.',
      },
    ],
  },

  // Arcade mode: the order of the journey, missions and upgrades mixed.
  ladder: ['bac', 'licence', 'trone', 'bts', 'bain', 'cisco', 'lv', 'lvmh', 'nxt', 'nexthink', 'bachelor', 'hotel', 'learnlink', 'rncp', 'ece', 'portfolio', 'next'],

  progress: {
    kicker: 'Arcade mode',
    heading: 'Progress',
    intro:
      'My journey, arcade style: bosses are the problems faced on missions, upgrades are my degrees and certifications. Every step cleared levels player 1 up.',
    start: 'Start arcade',
    resume: 'Resume arcade',
    restart: 'Start over',
    level: 'Level',
    steps: 'steps cleared',
    ladderLabel: 'Steps of the journey',
    boss: 'Mission',
    against: 'vs',
    upgrade: 'Upgrade',
    cleared: 'Cleared',
    obtained: 'Earned',
    inProgress: 'In progress',
    locked: 'To unlock',
    fight: 'Fight',
    see: 'View',
  },

  upgradeScreen: {
    banner: 'Upgrade!',
    perksTitle: 'New skills',
    levelUp: 'Level',
    continue: 'Continue',
    toProgress: 'See progress',
    certs: 'Certificates included',
    lockedBanner: 'To be continued…',
    lockedText: 'The next upgrade is being written right now. And the next mission might be with you.',
    toContact: 'Offer a mission',
  },

  moves: {
    kicker: 'Move list',
    heading: 'Skills',
    demo: 'Show the motion',
    intro:
      'My skills, as motion inputs. Perform them on the keyboard (arrows or WASD + J/K) or a gamepad: every successful move lights up.',
    legend: [
      ['P', 'Punch: J'],
      ['K', 'Kick: K'],
      ['6', 'Forward'],
      ['2', 'Down'],
    ],
    progress: 'moves landed',
    tapHint: 'On mobile: tap a move to see its motion.',
    allFound: 'Move list complete! Secret mission unlocked.',
    groups: [
      {
        title: 'Specials · Governance & access',
        moves: [
          { id: 'ca', name: 'Conditional Access', input: '236P', desc: 'Microsoft Entra ID policies: MFA, guest accounts, access conditions, staged rollout.' },
          { id: 'rbac', name: 'RBAC Guard', input: '41236K', desc: 'Roles, groups and rights: least privilege across Active Directory, Entra ID and applications.' },
          { id: 'runbook', name: 'Access Request', input: '623K', desc: 'Self-service request path (Power Apps) executed by Azure Automation.' },
          { id: 'mfa', name: 'Second Factor', input: '214P', desc: 'MFA, TOTP (RFC 6238), OAuth 2.0 and OpenID Connect.' },
        ],
      },
      {
        title: 'Specials · Microsoft 365 & automation',
        moves: [
          { id: 'm365', name: 'M365 Combo', input: '41236P', desc: 'Exchange Online, Teams, SharePoint: accounts, access and external collaboration.' },
          { id: 'ps', name: 'PowerShell Barrage', input: '236K', desc: 'Scripts, REST APIs, reports and scheduled tasks.' },
          { id: 'graph', name: 'Graph Call', input: '63214P', desc: 'Microsoft Graph API: users, groups, mail.' },
          { id: 'vault', name: 'Vault', input: '22P', desc: 'Azure Key Vault: secrets stay out of the code.' },
          { id: 'flow', name: 'Flow', input: '214K', desc: 'Power Automate for everyday processes.' },
        ],
      },
      {
        title: 'Specials · Workplace',
        moves: [
          { id: 'nexthink', name: 'Nexthink Scan', input: '623P', desc: 'NQL queries, Remote Actions, campaigns and DEX score.' },
          { id: 'ticket', name: 'Ticket Rush', input: '66P', desc: 'Support from L1 to L3 and incidents in ServiceNow (Bain & Company).' },
        ],
      },
    ],
    super: { id: 'zt', name: 'Zero Trust', input: '236236PK', desc: 'Never trust, always verify: governance, access control and monitoring combined.' },
    superTitle: 'Super',
    normalsTitle: 'Normals · Dev & DevOps',
    normals: ['JavaScript', 'Node.js', 'Express', 'React', 'MongoDB', 'PostgreSQL', 'Java', 'C#', 'Python', 'Docker', 'GitHub Actions', 'Prometheus', 'Grafana', 'Jest', 'Git'],
  },

  profile: {
    heading: 'Fighter card',
    name: 'Fodié Marega',
    tag: 'MRGMF',
    rows: [
      ['Class', 'End User Architect (apprenticeship at Louis Vuitton)'],
      ['Teams', 'Louis Vuitton (since 2025) · Bain & Company (2023 – 2025)'],
      ['Ally', 'Nexthink (certified ×2)'],
      ['Specialty', 'IAM: identity governance and architecture'],
      ['Style', 'Least privilege · Conditional Access · Automation'],
      ['Weapon of choice', 'PowerShell'],
      ['Signature move', 'Conditional Access (236P)'],
      ['Weakness', 'Passwords on their own'],
      ['Off the ring', 'Fighting games (FGC) and trading card games'],
    ],
    bio: 'My field: identity governance and architecture. Defining who accesses what and under which conditions, then making it verifiable and automated, from the Microsoft 365 tenant down to application code.',
    quoteLabel: 'Win quote',
    quote: '“Access is earned. And verified.”',
    costume: 'Colour',
    costumes: ['P1 Blue', 'P2 Red', 'Neon Green', 'Gold', 'Shadow'],
  },

  contact: {
    banner: 'Here comes a challenger!',
    heading: 'Contact',
    text: 'A project, a question about identity governance or automation, or just fancy a rematch? Write to me.',
    email: { user: 'fodiemarega91', domain: 'gmail.com' },
    emailLabel: 'Send an email',
    copy: 'Copy address',
    copied: 'Address copied!',
    copyFail: 'Could not copy: the address is shown on screen.',
    linkedin: 'https://www.linkedin.com/in/fodi%C3%A9marega/',
    github: 'https://github.com/MrgMF',
    continue: 'Continue?',
    gameOver: 'Game over? Not if you write to me.',
  },

  notFound: {
    heading: 'Game over',
    text: 'This page does not exist (or no longer does). You still have one credit.',
    continue: 'Continue?',
    cta: 'Back to the title screen',
  },

  konami: 'Code accepted!',
};
