// English content. Same structure as fr.mjs.

export default {
  lang: 'en',
  locale: 'en_GB',
  dir: 'en/',
  alternate: { lang: 'fr', dir: '', label: 'FR', name: 'Version française' },

  meta: {
    title: 'MRGMF · Fodié Marega: IAM, identity governance and architecture',
    description:
      'The playable portfolio of Fodié Marega, End User Architect specialising in IAM: identity governance and architecture (Microsoft Entra ID, Conditional Access), cloud automation (PowerShell, Azure) and development, arcade style.',
    ogAlt: 'Arcade-style title screen: MRGMF, Zero Trust Fighter.',
    notFoundTitle: 'Game over · MRGMF',
  },

  ui: {
    skip: 'Skip to content',
    nav: 'Main navigation',
    screens: {
      title: 'Title screen',
      select: 'Select',
      moves: 'Move list',
      profile: 'Profile',
      contact: 'Contact',
      stage: 'Stage',
    },
    sound: 'Sound',
    on: 'ON',
    off: 'OFF',
    readingMode: 'Reading mode',
    arcadeMode: 'Arcade mode',
    help: 'Controls',
    helpShort: 'Help',
    close: 'Close',
    back: 'Back',
    langSwitch: 'Passer en français',
    toastSoundOn: 'Sound on',
    toastSoundOff: 'Sound off',
    toastReading: 'Reading mode',
    toastArcade: 'Arcade mode',
    announceScreen: 'Screen',
    padConnected: 'Gamepad connected',
    footer: 'Handmade, no framework.',
    source: 'Source code',
    helpItems: [
      ['Arrows or WASD', 'Move, choose'],
      ['Enter or J', 'Confirm · punch (P)'],
      ['K', 'Kick (K)'],
      ['Esc', 'Back'],
      ['M', 'Toggle sound'],
      ['?', 'Show this help'],
      ['Gamepad', 'D-pad + A (confirm) / B (back)'],
    ],
    helpNote:
      'Motions (236P, 623K…) use fighting-game numpad notation: 2 = down, 6 = forward, 3 = down-forward.',
  },

  title: {
    logo: 'MRGMF',
    subtitle: 'Zero Trust Fighter',
    tagline: 'Secure the access. Automate the rest.',
    role: 'IAM · Identity governance & architecture',
    blurb:
      'The playable portfolio of Fodié Marega, End User Architect specialising in IAM: who has access to what, why, and how to prove it. Pick an opponent: every fight is a project.',
    start: 'Press start',
    startHint: 'Enter, click or tap',
    credit: 'Credit 01',
    reading: 'No time to play? Reading mode',
  },

  select: {
    heading: 'Choose your opponent',
    menuLabel: 'Select menu',
    readingHeading: 'Projects',
    readingIntro: 'Every project is a fight against one specific problem. Meet the opponents.',
    p1: 'Player 1',
    p2: 'Opponent',
    boss: 'Boss',
    hints: 'Arrows / WASD: choose · Enter or J: fight · Esc: back',
    random: { name: 'Random', tagline: 'Let fate pick your opponent.' },
    locked: { name: '???', tagline: 'Secret opponent. Rumour says an old code unlocks it…' },
    lockedToast: 'Locked. Try a famous code…',
    unlockedToast: 'New challenger: ARCHIVES',
    menu: [
      { id: 'moves', label: 'Move list', hint: 'My skills, as motion inputs' },
      { id: 'profile', label: 'Profile', hint: 'Fighter card' },
      { id: 'contact', label: 'Contact', hint: 'Challenge player 1' },
    ],
  },

  fight: {
    round: 'Round 1',
    fight: 'Fight!',
    ko: 'K.O.',
    perfect: 'Perfect',
    hits: 'hits',
    hit: 'hit',
    special: 'Special!',
    super: 'Super!',
    attack: 'Attack',
    skip: 'Skip the fight',
    replay: 'Play again',
    next: 'Next opponent',
    toSelect: 'Back to select',
    results: 'Results',
    stack: 'Arsenal',
    combo: 'Combo',
    opponent: 'Opponent',
    controlsHint: 'Hit with J or the button. Special motions count double.',
    commentaryIdle: 'Press “Attack” to start the combo.',
    vs: 'VS',
  },

  stages: [
    {
      id: 'learnlink',
      tile: 'LearnLink',
      name: 'LearnLink',
      kicker: 'Stage 01 · 2026 · Solo project',
      tagline: 'A secure e-learning platform: from course to verifiable certificate.',
      meta: ['2026', 'Solo', 'Node · React · MongoDB · PostgreSQL'],
      boss: {
        name: 'Brute Force',
        sprite: 'ram',
        desc: 'Keeps trying passwords until an account gives in.',
      },
      intro:
        'My final-year project: free courses and a certificate anyone can verify, without ever letting an account fall. Designed, built and tested solo, all the way to containers and monitoring.',
      hits: [
        { name: 'bcrypt ×12', desc: 'Passwords hashed with bcrypt (12 rounds): even if stolen, they stay useless.' },
        { name: 'TOTP · RFC 6238', desc: 'App-based second factor (Google Authenticator, Authy), with backup codes.' },
        { name: 'OAuth 2.0', desc: 'Sign in with Google or GitHub, no new password to remember.' },
        { name: 'Anti brute-force', desc: 'Adaptive CAPTCHA after 3 failures, temporary lockout at 10, security alert at 15.' },
        { name: 'RBAC · 5 roles', desc: 'Student, trainer, manager, curriculum lead, admin: each with its own rights, enforced server-side.' },
        { name: 'SIEM log', desc: 'Authentication events as normalised JSON, Prometheus metrics and Grafana dashboards.' },
      ],
      super: {
        name: 'Verifiable certificate',
        desc: 'QR code and public page: a recruiter checks a certificate in one scan, no account needed.',
      },
      results: [
        { value: '17', label: 'Jest tests run in CI' },
        { value: '8', label: 'Docker Compose services' },
        { value: '5', label: 'OWASP Top 10 risks covered' },
        { value: '2', label: 'blocking bugs found in QA, fixed' },
      ],
      stack: ['Node.js', 'Express 5', 'React 19', 'Vite', 'Tailwind', 'MongoDB', 'PostgreSQL', 'Redis', 'BullMQ', 'Socket.io', 'Stripe', 'Docker', 'GitHub Actions', 'Prometheus', 'Grafana', 'Jest'],
      note: 'Private code: demo on request.',
      links: [],
    },
    {
      id: 'automation',
      tile: 'IAM Ops',
      name: 'Identity governance',
      kicker: 'Stage 02 · Since 2025 · Apprenticeship at Louis Vuitton',
      tagline: 'Governing and securing access in a Microsoft 365 tenant, then automating whatever can be.',
      meta: ['Since 2025', 'Apprenticeship', 'Entra ID · Conditional Access · Azure'],
      boss: {
        name: 'Implicit Trust',
        sprite: 'ghost',
        desc: 'Assumes an access is legitimate because it has always worked.',
      },
      intro:
        'As an End User Architect apprentice in the IT department of Louis Vuitton, I work on identity governance in Microsoft 365: who accesses what, under which conditions, and how it is traced, at the scale of a large organisation. Internal details stay internal.',
      hits: [
        { name: 'Conditional Access', desc: 'A Microsoft Entra ID policy requiring MFA for guest accounts.' },
        { name: 'Report-only mode', desc: 'Measure the real impact of a policy before switching it on.' },
        { name: 'Ring deployment', desc: 'Gradual rollout, group by group, so nobody gets locked out.' },
        { name: 'PowerShell Barrage', desc: 'Automated monitoring report: REST API inventory, diff against the previous run, alerts.' },
        { name: 'Key Vault Guard', desc: 'Server-to-server OAuth 2.0, secrets kept in Azure Key Vault: never in the script.' },
        { name: 'Graph Call', desc: 'Report delivered through Microsoft Graph, on a schedule.' },
        { name: 'Access request', desc: 'Group access requested self-service in Power Apps, then applied by Azure Automation.' },
        { name: 'DNS · CDN · TLS', desc: 'Event web access going live: subdomain, CDN, certificate, opening on schedule.' },
      ],
      super: {
        name: 'Zero Trust',
        desc: 'Never trust, always verify: every access is explicit, logged and verifiable.',
      },
      results: [
        { value: '3', label: 'workstreams: guest MFA, automated monitoring, event access' },
        { value: '2', label: 'shipped to production' },
        { value: '0', label: 'incidents on event access' },
      ],
      stack: ['Microsoft Entra ID', 'Conditional Access', 'Microsoft 365', 'PowerShell', 'Azure Key Vault', 'Azure Automation', 'Microsoft Graph', 'Power Apps', 'Power Automate', 'Nexthink', 'REST APIs', 'OAuth 2.0'],
      note: 'Apprenticeship work: no public code.',
      links: [],
    },
    {
      id: 'hotel',
      tile: 'Hotel.java',
      name: 'Hotel.java',
      kicker: 'Stage 03 · 2025 · Pair project',
      tagline: 'Hotel management in Java: rooms, guests, bookings and services.',
      meta: ['2025', 'Duo', 'Java · OOP'],
      boss: {
        name: 'Overbooking',
        sprite: 'bell',
        desc: 'Two guests, one room, zero business rules.',
      },
      intro:
        'A school project with a teammate: model a hotel with object-oriented programming, from the room to the bill. I owned the guest booking flow and the services logic.',
      hits: [
        { name: 'Abstract class', desc: 'Room sets the contract; Single, Double and Suite refine it.' },
        { name: 'Polymorphism', desc: 'Each room type prices itself, and the Suite (jacuzzi, balcony) overrides the calculation.' },
        { name: 'java.time', desc: 'Number of nights computed from real dates, no hacks.' },
        { name: 'À la carte services', desc: 'Breakfast, spa… added to the booking and billed.' },
        { name: 'Filtered search', desc: 'Rooms by number, by type or under a maximum budget.' },
      ],
      super: {
        name: 'Final bill',
        desc: 'Room + services: the total price computes itself, booking by booking.',
      },
      results: [
        { value: '9', label: 'Java classes' },
        { value: '3', label: 'room types' },
        { value: '2', label: 'developers' },
      ],
      stack: ['Java', 'OOP', 'java.time', 'Collections', 'Eclipse', 'Git'],
      note: 'Private code (school project).',
      links: [],
    },
    {
      id: 'trone',
      tile: 'ProjecTTrone',
      name: 'ProjecTTrone',
      kicker: 'Stage 04 · 2023 · Team of three',
      tagline: 'A 3D action game built by three people, from Unreal Engine to Unity.',
      meta: ['2023', 'Trio', 'Unity · C# · Unreal'],
      boss: {
        name: 'The 3D Engine',
        sprite: 'cube',
        desc: 'Physics, cameras, collisions: a whole world to tame.',
      },
      intro:
        'My first big team project: a medieval 3D town to explore, with items and weapons to pick up. A V1 in Unreal Engine, then a V2 in Unity. I built the menus, the inventory and item pickup, and handled branch merges.',
      hits: [
        { name: 'V1 · Unreal Engine', desc: 'First prototype in C++ and Blueprints.' },
        { name: 'V2 · Unity 2022', desc: 'Rebuilt in C# to iterate faster.' },
        { name: 'Third-person camera', desc: 'Character controller and a camera that follows the player.' },
        { name: 'Inventory', desc: 'Items and data kept apart (Item / ItemData), panel toggled with the I key.' },
        { name: 'Item pickup', desc: 'Raycast detection: “Press E” as soon as an item is in range.' },
        { name: 'Team Git', desc: 'One branch per feature (menu, map, items), then merge.' },
      ],
      super: {
        name: 'Medieval town',
        desc: 'Character, map and items brought together in one playable scene.',
      },
      results: [
        { value: '3', label: 'developers' },
        { value: '2', label: 'game engines' },
        { value: '3', label: 'scenes (menu, town, sandbox)' },
      ],
      stack: ['Unity', 'C#', 'Unreal Engine', 'C++', 'Blueprints', 'Git'],
      note: 'Private code.',
      links: [],
    },
    {
      id: 'portfolio',
      tile: 'Portfolio',
      name: 'This portfolio',
      kicker: 'Stage 05 · 2026 · Solo project',
      tagline: 'A playable portfolio, handmade, no framework.',
      meta: ['2026', 'Solo', 'HTML · CSS · JS'],
      boss: {
        name: 'The Boring Résumé',
        sprite: 'paper',
        desc: 'One page, bullet points, and nobody reads to the end.',
      },
      intro:
        'Instead of yet another résumé, an arcade cabinet: every project is an opponent, every skill a motion input. Everything is handmade and still readable without JavaScript.',
      hits: [
        { name: 'Zero framework', desc: 'Plain HTML, CSS and JavaScript, as ES modules.' },
        { name: 'Homemade build', desc: 'A dependency-free Node generator outputs the FR and EN pages.' },
        { name: 'SVG pixel art', desc: 'Sprites drawn in code, rendered as crisp SVG at any size.' },
        { name: 'Input buffer', desc: 'Fighting-game motion detection (236P, 623K…), AZERTY or QWERTY.' },
        { name: 'Gamepad', desc: 'Gamepad API: plug in your pad or arcade stick.' },
        { name: 'Web Audio', desc: 'Sound effects synthesised live, muted by default.' },
      ],
      super: {
        name: 'Reading mode',
        desc: 'A calm, accessible version with no animation, one click away.',
      },
      results: [
        { value: '0', label: 'runtime dependencies' },
        { value: '2', label: 'languages' },
        { value: '∞', label: 'continues' },
      ],
      stack: ['HTML', 'CSS', 'JavaScript', 'Node.js', 'SVG', 'Web Audio', 'Gamepad API', 'GitHub Actions', 'GitHub Pages'],
      note: '',
      links: [{ label: 'Source code', href: 'https://github.com/MrgMF/MRGMF.github.io' }],
    },
    {
      id: 'archives',
      secret: true,
      tile: 'Archives',
      name: 'Archives',
      kicker: 'Secret stage · 2023 → 2025',
      tagline: 'The first rounds.',
      meta: ['2023 → 2025', 'Early days', 'HTML · PHP · React'],
      boss: {
        name: 'The Floppy Disk',
        sprite: 'floppy',
        desc: 'It keeps everything. Even the first attempts.',
      },
      intro: 'Opponent unlocked! Here are the earlier projects: not perfect, but that is where it all started.',
      hits: [
        { name: 'ArtisteCity · 2023', desc: 'A social network for artists: gallery, track previews, file uploads (HTML, CSS, PHP).' },
        { name: 'Tutor matching · 2025', desc: 'Interactive student / teacher mock-up: profiles, chat, settings (React, TypeScript, prototyped with Figma Make).' },
      ],
      super: {
        name: 'First website',
        desc: 'An HTML résumé on GitHub Pages. This portfolio took its place.',
      },
      results: [
        { value: '2021', label: 'first GitHub account' },
        { value: '2023', label: 'first projects online' },
      ],
      stack: ['HTML', 'CSS', 'PHP', 'React', 'TypeScript', 'Figma'],
      note: '',
      links: [],
    },
  ],

  moves: {
    heading: 'Move list',
    demo: 'Show the motion',
    intro:
      'My skills, as motion inputs. Perform them on the keyboard (arrows or WASD + J/K) or a gamepad: every successful move lights up.',
    legend: [
      ['P', 'Punch: J'],
      ['K', 'Kick: K'],
      ['6', 'Forward (→)'],
      ['2', 'Down (↓)'],
    ],
    progress: 'moves landed',
    tapHint: 'On mobile: tap a move to see its motion.',
    allFound: 'Move list complete! Secret opponent unlocked.',
    groups: [
      {
        title: 'Specials · Governance & access',
        moves: [
          { id: 'ca', name: 'Conditional Access', input: '236P', desc: 'Microsoft Entra ID policies: MFA, guest accounts, access conditions, staged rollout.' },
          { id: 'rbac', name: 'RBAC Guard', input: '41236K', desc: 'Roles, groups and rights: least privilege across Active Directory, Entra ID and applications.' },
          { id: 'runbook', name: 'Access Request', input: '623K', desc: 'Self-service request path (Power Apps) executed by Azure Automation.' },
          { id: 'mfa', name: 'Second Factor', input: '214P', desc: 'MFA, TOTP (RFC 6238), OAuth 2.0 and OpenID Connect.' },
        ],
      },
      {
        title: 'Specials · Automation',
        moves: [
          { id: 'ps', name: 'PowerShell Barrage', input: '236K', desc: 'Scripts, REST APIs, reports and scheduled tasks.' },
          { id: 'vault', name: 'Vault', input: '22P', desc: 'Azure Key Vault: secrets stay out of the code.' },
          { id: 'graph', name: 'Graph Call', input: '63214P', desc: 'Microsoft Graph API: users, groups, mail.' },
          { id: 'flow', name: 'Flow', input: '214K', desc: 'Power Automate for everyday processes.' },
        ],
      },
      {
        title: 'Specials · Workplace',
        moves: [
          { id: 'nexthink', name: 'Compliance Scan', input: '623P', desc: 'Nexthink: fleet visibility and compliance.' },
          { id: 'ticket', name: 'Ticket Rush', input: '66P', desc: 'Level 1/2 support and incidents in ServiceNow.' },
          { id: 'm365', name: 'M365 Combo', input: '41236P', desc: 'Exchange Online, Teams, SharePoint.' },
        ],
      },
    ],
    super: { id: 'zt', name: 'Zero Trust', input: '236236PK', desc: 'Never trust, always verify: governance, access control and monitoring combined.' },
    superTitle: 'Super',
    normalsTitle: 'Normals · Dev & DevOps',
    normals: ['JavaScript', 'Node.js', 'Express', 'React', 'MongoDB', 'PostgreSQL', 'Java', 'C#', 'Python', 'Docker', 'GitHub Actions', 'Prometheus', 'Grafana', 'Jest', 'Git'],
  },

  profile: {
    heading: 'Fighter card',
    name: 'Fodié Marega',
    tag: 'MRGMF',
    rows: [
      ['Class', 'End User Architect (apprentice)'],
      ['Specialty', 'IAM: identity governance and architecture'],
      ['Style', 'Least privilege · Conditional Access · Automation'],
      ['Weapon of choice', 'PowerShell'],
      ['Signature move', 'Conditional Access (236P)'],
      ['Weakness', 'Passwords on their own'],
      ['Off the ring', 'Fighting games (FGC) and trading card games'],
    ],
    bio: 'My field: identity governance and architecture. Defining who accesses what and under which conditions, then making it verifiable and automated, from the Microsoft 365 tenant down to application code.',
    quoteLabel: 'Win quote',
    quote: '“Access is earned. And verified.”',
    costume: 'Colour',
    costumes: ['P1 Blue', 'P2 Red', 'Neon Green', 'Gold', 'Shadow'],
  },

  contact: {
    banner: 'Here comes a challenger!',
    heading: 'Contact',
    text: 'A project, a question about identity governance or automation, or just fancy a rematch? Write to me.',
    email: { user: 'fodiemarega91', domain: 'gmail.com' },
    emailLabel: 'Send an email',
    copy: 'Copy address',
    copied: 'Address copied!',
    copyFail: 'Could not copy: the address is shown on screen.',
    linkedin: 'https://www.linkedin.com/in/fodi%C3%A9marega/',
    github: 'https://github.com/MrgMF',
    continue: 'Continue?',
    gameOver: 'Game over? Not if you write to me.',
  },

  notFound: {
    heading: 'Game over',
    text: 'This page does not exist (or no longer does). You still have one credit.',
    continue: 'Continue?',
    cta: 'Back to the title screen',
  },

  konami: 'Code accepted!',
};
