// Contenu FR du portfolio. Tout le texte du site vit ici (et dans en.mjs) :
// modifier une phrase = modifier ce fichier puis lancer `npm run build`.

export default {
  lang: 'fr',
  locale: 'fr_FR',
  dir: '',
  alternate: { lang: 'en', dir: 'en/', label: 'EN', name: 'English version' },

  meta: {
    title: 'MRGMF · Fodié Marega : IAM, gouvernance et architecture des identités',
    description:
      "Le portfolio jouable de Fodié Marega, End User Architect spécialisé IAM : gouvernance et architecture des identités (Microsoft Entra ID, accès conditionnel), automatisation cloud (PowerShell, Azure) et développement, façon borne d'arcade.",
    ogAlt: 'Écran titre façon borne d’arcade : MRGMF, Zero Trust Fighter.',
    notFoundTitle: 'Game over · MRGMF',
  },

  ui: {
    skip: 'Aller au contenu',
    nav: 'Navigation principale',
    screens: {
      title: 'Écran titre',
      select: 'Sélection',
      moves: 'Move list',
      profile: 'Profil',
      contact: 'Contact',
      stage: 'Combat',
    },
    sound: 'Son',
    on: 'ON',
    off: 'OFF',
    readingMode: 'Mode lecture',
    arcadeMode: 'Mode arcade',
    help: 'Commandes',
    helpShort: 'Aide',
    close: 'Fermer',
    back: 'Retour',
    langSwitch: 'Switch to English',
    toastSoundOn: 'Son activé',
    toastSoundOff: 'Son coupé',
    toastReading: 'Mode lecture',
    toastArcade: 'Mode arcade',
    announceScreen: 'Écran',
    padConnected: 'Manette connectée',
    footer: 'Fait main, sans framework.',
    source: 'Code source',
    helpItems: [
      ['Flèches ou ZQSD', 'Se déplacer, choisir'],
      ['Entrée ou J', 'Valider · coup de poing (P)'],
      ['K', 'Coup de pied (K)'],
      ['Échap', 'Retour'],
      ['M', 'Couper / activer le son'],
      ['?', 'Afficher cette aide'],
      ['Manette', 'Croix + A (valider) / B (retour)'],
    ],
    helpNote:
      'Les manipulations (236P, 623K…) utilisent la notation « numpad » des jeux de combat : 2 = bas, 6 = avant, 3 = bas-avant.',
  },

  title: {
    logo: 'MRGMF',
    subtitle: 'Zero Trust Fighter',
    tagline: 'Sécuriser les accès. Automatiser le reste.',
    role: 'IAM · Gouvernance & architecture des identités',
    blurb:
      "Le portfolio jouable de Fodié Marega, End User Architect spécialisé IAM : qui a accès à quoi, pourquoi, et comment le prouver. Choisis un adversaire, chaque combat est un projet.",
    start: 'Press start',
    startHint: 'Entrée, clic ou tap',
    credit: 'Crédit 01',
    reading: 'Pas le temps de jouer ? Mode lecture',
  },

  select: {
    heading: 'Choisis ton adversaire',
    menuLabel: 'Menu de sélection',
    readingHeading: 'Projets',
    readingIntro: 'Chaque projet est un combat contre un problème précis. Voici les adversaires.',
    p1: 'Joueur 1',
    p2: 'Adversaire',
    boss: 'Boss',
    hints: 'Flèches / ZQSD : choisir · Entrée ou J : combattre · Échap : retour',
    random: { name: 'Aléatoire', tagline: 'Laisse le hasard choisir ton adversaire.' },
    locked: { name: '???', tagline: 'Adversaire secret. Il paraît qu’un vieux code le débloque…' },
    lockedToast: 'Verrouillé. Essaie un code célèbre…',
    unlockedToast: 'Nouvel adversaire : ARCHIVES',
    menu: [
      { id: 'moves', label: 'Move list', hint: 'Mes compétences, en manipulations' },
      { id: 'profile', label: 'Profil', hint: 'Fiche combattant' },
      { id: 'contact', label: 'Contact', hint: 'Défier le joueur 1' },
    ],
  },

  fight: {
    round: 'Round 1',
    fight: 'Fight !',
    ko: 'K.O.',
    perfect: 'Perfect',
    hits: 'hits',
    hit: 'hit',
    special: 'Spécial !',
    super: 'Super !',
    attack: 'Attaquer',
    skip: 'Passer le combat',
    replay: 'Rejouer',
    next: 'Adversaire suivant',
    toSelect: 'Retour à la sélection',
    results: 'Résultat',
    stack: 'Arsenal',
    combo: 'Combo',
    opponent: 'Adversaire',
    controlsHint: 'Frappe avec J ou le bouton. Les manipulations spéciales comptent double.',
    commentaryIdle: 'Appuie sur « Attaquer » pour lancer le combo.',
    vs: 'VS',
  },

  stages: [
    {
      id: 'learnlink',
      tile: 'LearnLink',
      name: 'LearnLink',
      kicker: 'Combat 01 · 2026 · Projet solo',
      tagline: 'Plateforme e-learning sécurisée : du cours au certificat vérifiable.',
      meta: ['2026', 'Solo', 'Node · React · MongoDB · PostgreSQL'],
      boss: {
        name: 'Brute Force',
        sprite: 'ram',
        desc: 'Enchaîne les mots de passe jusqu’à ce qu’un compte cède.',
      },
      intro:
        "Mon projet de fin d'études : des cours gratuits et une certification que n'importe qui peut vérifier, sans jamais laisser un compte tomber. Conçu, développé et testé en solo, jusqu'à la conteneurisation et la supervision.",
      hits: [
        { name: 'bcrypt ×12', desc: 'Mots de passe hachés avec bcrypt (12 tours) : même volés, ils restent inexploitables.' },
        { name: 'TOTP · RFC 6238', desc: 'Second facteur par application (Google Authenticator, Authy), codes de secours inclus.' },
        { name: 'OAuth 2.0', desc: 'Connexion avec Google ou GitHub, sans nouveau mot de passe à retenir.' },
        { name: 'Anti brute-force', desc: 'CAPTCHA adaptatif dès 3 échecs, verrouillage temporaire à 10, alerte de sécurité à 15.' },
        { name: 'RBAC · 5 rôles', desc: 'Étudiant, formateur, gestionnaire, responsable pédagogique, admin : chacun ses droits, contrôlés côté serveur.' },
        { name: 'Journal SIEM', desc: 'Événements d’authentification en JSON normalisé, métriques Prometheus et tableaux de bord Grafana.' },
      ],
      super: {
        name: 'Certificat vérifiable',
        desc: 'QR code et page publique : un recruteur vérifie l’authenticité d’un certificat en un scan, sans compte.',
      },
      results: [
        { value: '17', label: 'tests Jest rejoués en CI' },
        { value: '8', label: 'services Docker Compose' },
        { value: '5', label: 'risques OWASP Top 10 couverts' },
        { value: '2', label: 'bugs bloquants trouvés en recette, corrigés' },
      ],
      stack: ['Node.js', 'Express 5', 'React 19', 'Vite', 'Tailwind', 'MongoDB', 'PostgreSQL', 'Redis', 'BullMQ', 'Socket.io', 'Stripe', 'Docker', 'GitHub Actions', 'Prometheus', 'Grafana', 'Jest'],
      note: 'Code privé : démo sur demande.',
      links: [],
    },
    {
      id: 'automation',
      tile: 'IAM Ops',
      name: 'Gouvernance des identités',
      kicker: 'Combat 02 · Depuis 2025 · Alternance chez Louis Vuitton',
      tagline: 'Gouverner et sécuriser les accès d’un tenant Microsoft 365, puis automatiser ce qui peut l’être.',
      meta: ['Depuis 2025', 'Alternance', 'Entra ID · Accès conditionnel · Azure'],
      boss: {
        name: 'Confiance implicite',
        sprite: 'ghost',
        desc: 'Considère qu’un accès est légitime parce qu’il a toujours marché.',
      },
      intro:
        "En alternance comme End User Architect à la DSI de Louis Vuitton, je travaille sur la gouvernance des identités dans Microsoft 365 : qui accède à quoi, sous quelles conditions, et comment le tracer, à l'échelle d'une grande organisation. Les détails internes restent en interne.",
      hits: [
        { name: 'Accès conditionnel', desc: 'Stratégie Microsoft Entra ID qui exige le MFA pour les comptes invités.' },
        { name: 'Mode rapport seul', desc: 'Mesurer l’impact réel d’une stratégie avant de l’activer.' },
        { name: 'Déploiement par anneaux', desc: 'Activation progressive, groupe par groupe, pour ne bloquer personne.' },
        { name: 'Rafale PowerShell', desc: 'Rapport de supervision automatisé : inventaire via API REST, comparaison avec l’exécution précédente, alertes.' },
        { name: 'Coffre Key Vault', desc: 'Authentification OAuth 2.0 serveur à serveur, secrets dans Azure Key Vault : jamais dans le script.' },
        { name: 'Appel Graph', desc: 'Rapport envoyé via Microsoft Graph, exécution planifiée.' },
        { name: 'Demande d’accès', desc: 'Accès aux groupes demandés en self-service via Power Apps, puis appliqués par Azure Automation.' },
        { name: 'DNS · CDN · TLS', desc: 'Mise en ligne d’accès web événementiels : sous-domaine, CDN, certificat, ouverture selon planning.' },
      ],
      super: {
        name: 'Zero Trust',
        desc: 'Ne jamais faire confiance, toujours vérifier : chaque accès est explicite, tracé et vérifiable.',
      },
      results: [
        { value: '3', label: 'chantiers menés : MFA des invités, supervision automatisée, accès événementiels' },
        { value: '2', label: 'passés en production' },
        { value: '0', label: 'incident sur les accès événementiels' },
      ],
      stack: ['Microsoft Entra ID', 'Accès conditionnel', 'Microsoft 365', 'PowerShell', 'Azure Key Vault', 'Azure Automation', 'Microsoft Graph', 'Power Apps', 'Power Automate', 'Nexthink', 'API REST', 'OAuth 2.0'],
      note: 'Réalisations en alternance : pas de code public.',
      links: [],
    },
    {
      id: 'hotel',
      tile: 'Hotel.java',
      name: 'Hotel.java',
      kicker: 'Combat 03 · 2025 · Projet en binôme',
      tagline: 'Gestion d’hôtel en Java : chambres, clients, réservations et services.',
      meta: ['2025', 'Duo', 'Java · POO'],
      boss: {
        name: 'Overbooking',
        sprite: 'bell',
        desc: 'Deux clients, une chambre, zéro règle métier.',
      },
      intro:
        "Projet d'école en binôme : modéliser un hôtel en programmation orientée objet, de la chambre à la facture. J'ai pris en charge le flux de réservation côté client et la logique des services.",
      hits: [
        { name: 'Classe abstraite', desc: 'Chambre fixe le contrat ; Simple, Double et Suite le précisent.' },
        { name: 'Polymorphisme', desc: 'Chaque type de chambre calcule son prix, la Suite (jacuzzi, balcon) surcharge le calcul.' },
        { name: 'java.time', desc: 'Nombre de nuits calculé à partir des dates, sans bricolage.' },
        { name: 'Services à la carte', desc: 'Petit-déjeuner, spa… ajoutés à la réservation et facturés.' },
        { name: 'Recherche filtrée', desc: 'Chambres par numéro, par type ou sous un budget maximum.' },
      ],
      super: {
        name: 'Facture totale',
        desc: 'Chambre + services : le prix final se calcule tout seul, réservation par réservation.',
      },
      results: [
        { value: '9', label: 'classes Java' },
        { value: '3', label: 'types de chambre' },
        { value: '2', label: 'développeurs' },
      ],
      stack: ['Java', 'POO', 'java.time', 'Collections', 'Eclipse', 'Git'],
      note: 'Code privé (projet d’école).',
      links: [],
    },
    {
      id: 'trone',
      tile: 'ProjecTTrone',
      name: 'ProjecTTrone',
      kicker: 'Combat 04 · 2023 · Projet à trois',
      tagline: 'Jeu d’action 3D développé à trois, d’Unreal Engine à Unity.',
      meta: ['2023', 'Trio', 'Unity · C# · Unreal'],
      boss: {
        name: 'Le moteur 3D',
        sprite: 'cube',
        desc: 'Physique, caméras, collisions : un monde entier à dompter.',
      },
      intro:
        'Mon premier gros projet d’équipe : une ville médiévale en 3D à explorer, des objets et des armes à ramasser. Une V1 sous Unreal Engine, puis une V2 sous Unity. J’ai codé les menus, l’inventaire et le ramassage, et géré les fusions de branches.',
      hits: [
        { name: 'V1 · Unreal Engine', desc: 'Premier prototype en C++ et Blueprints.' },
        { name: 'V2 · Unity 2022', desc: 'Reprise en C# pour itérer plus vite.' },
        { name: 'Caméra 3e personne', desc: 'Contrôleur de personnage et caméra qui suit le joueur.' },
        { name: 'Inventaire', desc: 'Objets et données séparés (Item / ItemData), panneau ouvert avec la touche I.' },
        { name: 'Ramassage', desc: 'Détection par raycast : « Press E » dès qu’un objet est à portée.' },
        { name: 'Git en équipe', desc: 'Une branche par fonctionnalité (menu, carte, objets), puis fusion.' },
      ],
      super: {
        name: 'Ville médiévale',
        desc: 'Personnage, carte et objets réunis dans une même scène jouable.',
      },
      results: [
        { value: '3', label: 'développeurs' },
        { value: '2', label: 'moteurs de jeu' },
        { value: '3', label: 'scènes (menu, ville, bac à sable)' },
      ],
      stack: ['Unity', 'C#', 'Unreal Engine', 'C++', 'Blueprints', 'Git'],
      note: 'Code privé.',
      links: [],
    },
    {
      id: 'portfolio',
      tile: 'Portfolio',
      name: 'Ce portfolio',
      kicker: 'Combat 05 · 2026 · Projet solo',
      tagline: 'Un portfolio jouable, fait main, sans framework.',
      meta: ['2026', 'Solo', 'HTML · CSS · JS'],
      boss: {
        name: 'Le CV ennuyeux',
        sprite: 'paper',
        desc: 'Une page, des puces, et personne ne lit jusqu’au bout.',
      },
      intro:
        'Plutôt qu’un CV de plus, une borne d’arcade : chaque projet est un adversaire, chaque compétence une manipulation. Tout est fait main et reste lisible sans JavaScript.',
      hits: [
        { name: 'Zéro framework', desc: 'HTML, CSS et JavaScript natifs, en modules ES.' },
        { name: 'Build maison', desc: 'Un générateur Node sans dépendance produit les pages FR et EN.' },
        { name: 'Pixel art en SVG', desc: 'Sprites dessinés par code, rendus en SVG net à n’importe quelle taille.' },
        { name: 'Buffer d’entrées', desc: 'Détection des manipulations façon jeu de combat (236P, 623K…), clavier AZERTY ou QWERTY.' },
        { name: 'Manette', desc: 'Gamepad API : branche ta manette ou ton stick arcade.' },
        { name: 'Web Audio', desc: 'Bruitages synthétisés en direct, coupés par défaut.' },
      ],
      super: {
        name: 'Mode lecture',
        desc: 'Une version sobre et accessible, sans animation, à un clic.',
      },
      results: [
        { value: '0', label: 'dépendance à l’exécution' },
        { value: '2', label: 'langues' },
        { value: '∞', label: 'continues' },
      ],
      stack: ['HTML', 'CSS', 'JavaScript', 'Node.js', 'SVG', 'Web Audio', 'Gamepad API', 'GitHub Actions', 'GitHub Pages'],
      note: '',
      links: [{ label: 'Code source', href: 'https://github.com/MrgMF/MRGMF.github.io' }],
    },
    {
      id: 'archives',
      secret: true,
      tile: 'Archives',
      name: 'Archives',
      kicker: 'Combat secret · 2023 → 2025',
      tagline: 'Les premiers rounds.',
      meta: ['2023 → 2025', 'Débuts', 'HTML · PHP · React'],
      boss: {
        name: 'La disquette',
        sprite: 'floppy',
        desc: 'Elle garde tout. Même les premiers essais.',
      },
      intro: 'Adversaire débloqué ! Voici les projets d’avant : pas parfaits, mais c’est là que tout a commencé.',
      hits: [
        { name: 'ArtisteCity · 2023', desc: 'Réseau social pour artistes : galerie, écoute de morceaux, envoi de fichiers (HTML, CSS, PHP).' },
        { name: 'Mise en relation · 2025', desc: 'Maquette interactive élèves / professeurs : profils, messagerie, réglages (React, TypeScript, prototypée avec Figma Make).' },
      ],
      super: {
        name: 'Premier site',
        desc: 'Un CV en HTML publié sur GitHub Pages. Ce portfolio a pris sa place.',
      },
      results: [
        { value: '2021', label: 'premier compte GitHub' },
        { value: '2023', label: 'premiers projets en ligne' },
      ],
      stack: ['HTML', 'CSS', 'PHP', 'React', 'TypeScript', 'Figma'],
      note: '',
      links: [],
    },
  ],

  moves: {
    heading: 'Move list',
    demo: 'Voir la manipulation',
    intro:
      'Mes compétences, en manipulations. Exécute-les au clavier (flèches ou ZQSD + J/K) ou à la manette : chaque coup réussi s’illumine.',
    legend: [
      ['P', 'Poing : J'],
      ['K', 'Pied : K'],
      ['6', 'Avant (→)'],
      ['2', 'Bas (↓)'],
    ],
    progress: 'manipulations réussies',
    tapHint: 'Sur mobile : touche un coup pour voir la manipulation.',
    allFound: 'Move list complète ! Adversaire secret débloqué.',
    groups: [
      {
        title: 'Spéciaux · Gouvernance & accès',
        moves: [
          { id: 'ca', name: 'Accès conditionnel', input: '236P', desc: 'Stratégies Microsoft Entra ID : MFA, comptes invités, conditions d’accès, déploiement progressif.' },
          { id: 'rbac', name: 'Garde RBAC', input: '41236K', desc: 'Rôles, groupes et droits : moindre privilège dans Active Directory, Entra ID et les applications.' },
          { id: 'runbook', name: 'Demande d’accès', input: '623K', desc: 'Circuit de demande en self-service (Power Apps) exécuté par Azure Automation.' },
          { id: 'mfa', name: 'Double facteur', input: '214P', desc: 'MFA, TOTP (RFC 6238), OAuth 2.0 et OpenID Connect.' },
        ],
      },
      {
        title: 'Spéciaux · Automatisation',
        moves: [
          { id: 'ps', name: 'Rafale PowerShell', input: '236K', desc: 'Scripts, API REST, rapports et tâches planifiées.' },
          { id: 'vault', name: 'Coffre-fort', input: '22P', desc: 'Azure Key Vault : les secrets restent hors du code.' },
          { id: 'graph', name: 'Appel Graph', input: '63214P', desc: 'Microsoft Graph API : utilisateurs, groupes, e-mails.' },
          { id: 'flow', name: 'Flow', input: '214K', desc: 'Power Automate pour les processus du quotidien.' },
        ],
      },
      {
        title: 'Spéciaux · Poste de travail',
        moves: [
          { id: 'nexthink', name: 'Scan de conformité', input: '623P', desc: 'Nexthink : visibilité et conformité du parc.' },
          { id: 'ticket', name: 'Ticket Rush', input: '66P', desc: 'Support N1/N2 et incidents via ServiceNow.' },
          { id: 'm365', name: 'Combo M365', input: '41236P', desc: 'Exchange Online, Teams, SharePoint.' },
        ],
      },
    ],
    super: { id: 'zt', name: 'Zero Trust', input: '236236PK', desc: 'Ne jamais faire confiance, toujours vérifier : gouvernance, contrôle d’accès et supervision réunis.' },
    superTitle: 'Super',
    normalsTitle: 'Normaux · Dév & DevOps',
    normals: ['JavaScript', 'Node.js', 'Express', 'React', 'MongoDB', 'PostgreSQL', 'Java', 'C#', 'Python', 'Docker', 'GitHub Actions', 'Prometheus', 'Grafana', 'Jest', 'Git'],
  },

  profile: {
    heading: 'Fiche combattant',
    name: 'Fodié Marega',
    tag: 'MRGMF',
    rows: [
      ['Classe', 'End User Architect (alternance)'],
      ['Spécialité', 'IAM : gouvernance et architecture des identités'],
      ['Style', 'Moindre privilège · Accès conditionnel · Automatisation'],
      ['Arme favorite', 'PowerShell'],
      ['Coup signature', 'Accès conditionnel (236P)'],
      ['Point faible', 'Les mots de passe tout seuls'],
      ['Hors du ring', 'Jeux de combat (FGC) et jeux de cartes à collectionner'],
    ],
    bio: 'Mon terrain : la gouvernance et l’architecture des identités. Définir qui accède à quoi et à quelles conditions, puis le rendre vérifiable et automatisé, du tenant Microsoft 365 jusqu’au code des applications.',
    quoteLabel: 'Phrase de victoire',
    quote: '« Un accès, ça se mérite. Et ça se vérifie. »',
    costume: 'Couleur',
    costumes: ['Bleu P1', 'Rouge P2', 'Vert néon', 'Or', 'Ombre'],
  },

  contact: {
    banner: 'Challenger en approche !',
    heading: 'Contact',
    text: 'Un projet, une question sur la gouvernance des identités ou l’automatisation, ou juste envie d’une revanche ? Écris-moi.',
    email: { user: 'fodiemarega91', domain: 'gmail.com' },
    emailLabel: 'Envoyer un e-mail',
    copy: 'Copier l’adresse',
    copied: 'Adresse copiée !',
    copyFail: 'Copie impossible : l’adresse est affichée à l’écran.',
    linkedin: 'https://www.linkedin.com/in/fodi%C3%A9marega/',
    github: 'https://github.com/MrgMF',
    continue: 'Continue ?',
    gameOver: 'Game over ? Pas si tu m’écris.',
  },

  notFound: {
    heading: 'Game over',
    text: 'Cette page n’existe pas (ou plus). Il te reste un crédit.',
    continue: 'Continue ?',
    cta: 'Retour à l’écran titre',
  },

  konami: 'Code accepté !',
};
