// Contenu FR du portfolio. Tout le texte du site vit ici (et dans en.mjs) :
// modifier une phrase = modifier ce fichier puis lancer `npm run build`.

export default {
  lang: 'fr',
  locale: 'fr_FR',
  dir: '',
  alternate: { lang: 'en', dir: 'en/', label: 'EN', name: 'English version' },

  meta: {
    title: 'MRGMF · Fodié Marega : IAM, gouvernance et architecture des identités',
    description:
      "Le portfolio jouable de Fodié Marega, End User Architect chez Louis Vuitton spécialisé IAM : gouvernance et architecture des identités, Microsoft 365, Nexthink et automatisation cloud, façon borne d'arcade.",
    ogAlt: 'Écran titre façon borne d’arcade : MRGMF, Zero Trust Fighter.',
    notFoundTitle: 'Game over · MRGMF',
  },

  ui: {
    skip: 'Aller au contenu',
    nav: 'Navigation principale',
    navItems: [
      { id: 'select', label: 'Projets', icon: 'grid' },
      { id: 'progress', label: 'Progression', icon: 'stairs' },
      { id: 'moves', label: 'Compétences', icon: 'bolt' },
      { id: 'profile', label: 'Profil', icon: 'user' },
      { id: 'contact', label: 'Contact', icon: 'mail' },
    ],
    screens: {
      title: 'Écran titre',
      select: 'Sélection',
      progress: 'Progression',
      moves: 'Compétences',
      profile: 'Profil',
      contact: 'Contact',
      stage: 'Combat',
      upgrade: 'Amélioration',
    },
    sound: 'Son',
    on: 'ON',
    off: 'OFF',
    readingMode: 'Mode lecture',
    arcadeMode: 'Mode arcade',
    help: 'Commandes',
    helpShort: 'Aide',
    close: 'Fermer',
    back: 'Retour',
    langSwitch: 'Switch to English',
    toastSoundOn: 'Son activé',
    toastSoundOff: 'Son coupé',
    toastReading: 'Mode lecture',
    toastArcade: 'Mode arcade',
    announceScreen: 'Écran',
    padConnected: 'Manette connectée',
    footer: 'Fait main, sans framework.',
    source: 'Code source',
    helpItems: [
      ['Flèches ou ZQSD', 'Se déplacer, choisir'],
      ['Entrée ou J', 'Valider · coup de poing (P)'],
      ['K', 'Coup de pied (K)'],
      ['Échap', 'Retour'],
      ['M', 'Couper / activer le son'],
      ['?', 'Afficher cette aide'],
      ['Manette', 'Croix + A (valider) / B (retour)'],
    ],
    helpNote:
      'Les manipulations (236P, 623K…) utilisent la notation « numpad » des jeux de combat : 2 = bas, 6 = avant, 3 = bas-avant.',
  },

  title: {
    logo: 'MRGMF',
    subtitle: 'Zero Trust Fighter',
    tagline: 'Sécuriser les accès. Automatiser le reste.',
    role: 'IAM · Gouvernance & architecture des identités',
    blurb:
      "Le portfolio jouable de Fodié Marega, End User Architect spécialisé IAM : qui a accès à quoi, pourquoi, et comment le prouver. Chaque boss est un problème à régler, chaque entreprise une équipe, chaque diplôme une amélioration.",
    start: 'Commencer',
    startHint: 'ou appuie sur Entrée',
    credit: 'Crédit 01',
    reading: 'Pas le temps de jouer ? Mode lecture',
  },

  select: {
    heading: 'Choisis ta mission',
    subtitle:
      'Chaque mission oppose le joueur 1 à un problème concret. Les entreprises, elles, sont dans son équipe. Tout reste lisible, même sans combattre.',
    tip: 'Astuce : flèches + Entrée, ou clique sur une mission.',
    readingHeading: 'Projets et expériences',
    readingIntro: 'Chaque mission est un combat contre un problème précis, mené en équipe ou en solo.',
    p1: 'Joueur 1',
    p2: 'Adversaire',
    mission: 'Mission',
    hints: 'Flèches / ZQSD : choisir · Entrée ou J : lancer la mission · Échap : retour',
    random: { name: 'Aléatoire', tagline: 'Laisse le hasard choisir ta mission.', crew: 'Surprise' },
    locked: { name: '???', tagline: 'Mission secrète. Il paraît qu’un vieux code la débloque…', boss: '?' },
    lockedToast: 'Verrouillé. Essaie un code célèbre…',
    unlockedToast: 'Nouvelle mission : ARCHIVES',
  },

  fight: {
    round: 'Round 1',
    fight: 'Fight !',
    ko: 'K.O.',
    perfect: 'Perfect',
    hits: 'hits',
    hit: 'hit',
    special: 'Spécial !',
    super: 'Super !',
    attack: 'Attaquer',
    skip: 'Passer le combat',
    replay: 'Rejouer',
    next: 'Suivant',
    toSelect: 'Retour aux missions',
    results: 'Résultat',
    stack: 'Arsenal',
    combo: 'Combo',
    highlights: 'Points forts',
    brief: 'Brief',
    tabsLabel: 'Contenu du combat',
    backToProjects: 'Toutes les missions',
    access: 'Accéder au projet',
    opponent: 'Adversaire',
    team: 'Équipe',
    assist: 'Assist',
    nextLabel: 'Prochaine étape',
    controlsHint: 'Frappe avec J ou le bouton. Les manipulations spéciales comptent double.',
    commentaryIdle: 'Appuie sur « Attaquer » pour lancer le combo, ou parcours les onglets.',
    vs: 'VS',
    perksTitle: 'Compétences gagnées',
  },

  // Ordre de la sélection : les expériences les plus récentes d'abord.
  stages: [
    {
      id: 'lv',
      team: 'lv',
      tile: 'End User Architect',
      name: 'End User Architect',
      kicker: 'Alternance chez Louis Vuitton · depuis 2025',
      tagline: 'Gouverner les identités et l’environnement de travail Microsoft 365, puis automatiser ce qui peut l’être.',
      meta: ['Depuis 2025', 'Alternance', 'M365 · Entra ID · Azure'],
      boss: {
        name: 'Confiance implicite',
        sprite: 'ghost',
        desc: 'Considère qu’un accès est légitime parce qu’il a toujours marché.',
      },
      intro:
        "En alternance dans l'équipe Digital Workplace de Louis Vuitton, je suis End User Architect : je travaille sur l'environnement Microsoft 365 et la gouvernance des identités. Qui accède à quoi, sous quelles conditions, et comment le tracer, à l'échelle d'une grande organisation. Les détails internes restent en interne.",
      hits: [
        { name: 'Tenant Microsoft 365', desc: 'Exchange Online, Teams, SharePoint : comptes, accès et collaboration avec l’extérieur.' },
        { name: 'Accès conditionnel', desc: 'Stratégie Microsoft Entra ID qui exige le MFA pour les comptes invités.' },
        { name: 'Mode rapport seul', desc: 'Mesurer l’impact réel d’une stratégie avant de l’activer.' },
        { name: 'Déploiement par anneaux', desc: 'Activation progressive, groupe par groupe, pour ne bloquer personne.' },
        { name: 'Demande d’accès', desc: 'Accès aux groupes demandés en self-service via Power Apps, puis appliqués par Azure Automation.' },
        { name: 'Rafale PowerShell', desc: 'Rapport de supervision automatisé (API REST, comparaison avec l’exécution précédente, alertes), envoyé via Microsoft Graph.' },
        { name: 'Coffre Key Vault', desc: 'Authentification OAuth 2.0 serveur à serveur, secrets stockés dans Azure Key Vault : jamais dans le script.' },
        { name: 'DNS · CDN · TLS', desc: 'Mise en ligne d’accès web événementiels : sous-domaine, CDN, certificat, ouverture selon planning.' },
      ],
      super: {
        name: 'Zero Trust',
        desc: 'Ne jamais faire confiance, toujours vérifier : chaque accès est explicite, tracé et vérifiable.',
      },
      results: [
        { value: '3', label: 'chantiers menés : MFA des invités, supervision automatisée, accès événementiels' },
        { value: '2', label: 'passés en production' },
        { value: '0', label: 'incident sur les accès événementiels' },
      ],
      stack: ['Microsoft 365', 'Exchange Online', 'Teams', 'SharePoint', 'Microsoft Entra ID', 'Accès conditionnel', 'PowerShell', 'Microsoft Graph', 'Azure Key Vault', 'Azure Automation', 'Power Apps', 'API Zoom'],
      note: 'Réalisations en alternance : pas de code public. La démo recrée le principe avec des stratégies génériques.',
      access: [{ label: 'Simulateur d’accès conditionnel', href: 'demos/acces-conditionnel/', kind: 'demo' }],
      perks: ['Microsoft 365', 'Accès conditionnel', 'Azure Automation'],
    },
    {
      id: 'nexthink',
      team: 'lv',
      assist: 'nexthink',
      tile: 'Expérience numérique',
      name: 'Expérience numérique',
      kicker: 'Alternance chez Louis Vuitton · depuis 2025',
      tagline: 'Voir ce que vivent les collaborateurs sur leur poste, et corriger avant l’appel au support.',
      meta: ['Depuis 2025', 'Alternance', 'Nexthink · NQL · DEX'],
      boss: {
        name: 'La Dérive',
        sprite: 'laptop',
        desc: 'Un poste sort de la conformité en silence… jusqu’à la panne.',
      },
      intro:
        'Avec Nexthink en renfort, je suis l’expérience numérique des collaborateurs (DEX) et la conformité du parc : repérer les postes qui dérivent, prévenir les utilisateurs concernés et corriger à distance.',
      hits: [
        { name: 'Requête NQL', desc: 'Investigations en NQL pour interroger l’état réel du parc.' },
        { name: 'Tableau de conformité', desc: 'Tableaux de bord de conformité du parc, partagés avec les équipes.' },
        { name: 'Remote Action', desc: 'Scripts de diagnostic et de remédiation poussés à distance sur les postes.' },
        { name: 'Campagne', desc: 'Sondages et messages ciblés envoyés aux collaborateurs concernés.' },
        { name: 'Alerte', desc: 'Alertes sur les incidents, pour agir avant que les tickets n’arrivent.' },
        { name: 'Score DEX', desc: 'Suivi du score d’expérience numérique pour mesurer l’effet des actions.' },
      ],
      super: {
        name: 'Remédiation proactive',
        desc: 'Détecter, prévenir, corriger : le problème est réglé avant d’être signalé.',
      },
      results: [
        { value: '2', label: 'certifications Nexthink Associate (2026)' },
        { value: '4', label: 'leviers : requêtes, remote actions, campagnes, alertes' },
      ],
      stack: ['Nexthink Infinity', 'NQL', 'Remote Actions', 'Campagnes', 'Alertes', 'Score DEX', 'PowerShell'],
      note: 'Réalisations en alternance. La démo utilise des données entièrement fictives.',
      access: [{ label: 'Console DEX (données fictives)', href: 'demos/nexthink/', kind: 'demo' }],
      perks: ['Nexthink', 'NQL', 'Score DEX'],
    },
    {
      id: 'learnlink',
      crew: 'Solo',
      tile: 'LearnLink',
      name: 'LearnLink',
      kicker: 'Projet de fin d’études · 2026 · solo',
      tagline: 'Plateforme e-learning sécurisée : du cours au certificat vérifiable.',
      meta: ['2026', 'Solo', 'Node · React · MongoDB · PostgreSQL'],
      boss: {
        name: 'Brute Force',
        sprite: 'ram',
        desc: 'Enchaîne les mots de passe jusqu’à ce qu’un compte cède.',
      },
      intro:
        "Mon projet de fin d'études : des cours gratuits et une certification que n'importe qui peut vérifier, sans jamais laisser un compte tomber. Conçu, développé et testé en solo, jusqu'à la conteneurisation et la supervision.",
      hits: [
        { name: 'bcrypt ×12', desc: 'Mots de passe hachés avec bcrypt (12 tours) : même volés, ils restent inexploitables.' },
        { name: 'TOTP · RFC 6238', desc: 'Second facteur par application (Google Authenticator, Authy), codes de secours inclus.' },
        { name: 'OAuth 2.0', desc: 'Connexion avec Google ou GitHub, sans nouveau mot de passe à retenir.' },
        { name: 'Anti brute-force', desc: 'CAPTCHA adaptatif dès 3 échecs, verrouillage temporaire à 10, alerte de sécurité à 15.' },
        { name: 'RBAC · 5 rôles', desc: 'Étudiant, formateur, gestionnaire, responsable pédagogique, admin : chacun ses droits, contrôlés côté serveur.' },
        { name: 'Journal SIEM', desc: 'Événements d’authentification en JSON normalisé, métriques Prometheus et tableaux de bord Grafana.' },
      ],
      super: {
        name: 'Certificat vérifiable',
        desc: 'QR code et page publique : un recruteur vérifie l’authenticité d’un certificat en un scan, sans compte.',
      },
      results: [
        { value: '17', label: 'tests Jest rejoués en CI' },
        { value: '8', label: 'services Docker Compose' },
        { value: '5', label: 'risques OWASP Top 10 couverts' },
        { value: '2', label: 'bugs bloquants trouvés en recette, corrigés' },
      ],
      stack: ['Node.js', 'Express 5', 'React 19', 'Vite', 'Tailwind', 'MongoDB', 'PostgreSQL', 'Redis', 'BullMQ', 'Socket.io', 'Stripe', 'Docker', 'GitHub Actions', 'Prometheus', 'Grafana', 'Jest'],
      note: 'Code privé (dossier de certification). La démo recrée les mécanismes de sécurité dans le navigateur.',
      access: [{ label: 'Connexion MFA en direct', href: 'demos/learnlink/', kind: 'demo' }],
      perks: ['Node.js', 'React', 'MFA / TOTP', 'Docker'],
    },
    {
      id: 'bain',
      team: 'bain',
      tile: 'Support IT',
      name: 'Support IT, jusqu’au N3',
      kicker: 'Alternance chez Bain & Company · 2023 – 2025',
      tagline: 'Du premier ticket au niveau 3 : deux ans à tenir le poste de travail d’un cabinet international.',
      meta: ['2023 – 2025', 'Alternance', 'ServiceNow · AD · PowerShell'],
      boss: {
        name: 'L’Hydre à tickets',
        sprite: 'hydra',
        desc: 'Un ticket fermé, deux qui repoussent.',
      },
      intro:
        'Deux ans d’alternance comme assistant IT chez Bain & Company France. J’ai commencé au niveau 1 et fini au niveau 3 : du diagnostic matériel jusqu’à l’administration et l’automatisation.',
      hits: [
        { name: 'N1 · Diagnostic', desc: 'Premier niveau : diagnostic et réparation du matériel, réponse directe aux utilisateurs.' },
        { name: 'N1 · Parc & stock', desc: 'Gestion du stock et de la flotte informatique, préparation des postes.' },
        { name: 'N2 · ServiceNow', desc: 'Prise en charge des incidents et des demandes de niveau 2 dans ServiceNow.' },
        { name: 'N2 · Active Directory', desc: 'Administration des comptes, des groupes et des droits d’accès.' },
        { name: 'N3 · Serveurs', desc: 'Troisième niveau : gestion des serveurs et des incidents les plus complexes.' },
        { name: 'N3 · Automatisation', desc: 'Tâches récurrentes automatisées en PowerShell et avec Power Automate.' },
      ],
      super: {
        name: 'Niveau 3 atteint',
        desc: 'De N1 à N3 en deux ans, au contact d’équipes IT locales et internationales.',
      },
      results: [
        { value: 'N3', label: 'atteint en deux ans, en partant du N1' },
        { value: '2', label: 'années d’alternance' },
        { value: 'FR · EN', label: 'équipes locales et internationales' },
      ],
      stack: ['ServiceNow', 'Active Directory', 'PowerShell', 'Power Automate', 'Windows', 'Microsoft 365', 'Matériel'],
      note: 'Expérience en entreprise. La démo recrée le triage du support sous forme de mini-jeu.',
      access: [{ label: 'Ticket Rush (mini-jeu)', href: 'demos/tickets/', kind: 'demo' }],
      perks: ['Support N1 à N3', 'Active Directory', 'ServiceNow'],
    },
    {
      id: 'hotel',
      crew: 'En binôme',
      tile: 'Hotel.java',
      name: 'Hotel.java',
      kicker: 'Projet d’école en binôme · 2025',
      tagline: 'Gestion d’hôtel en Java : chambres, clients, réservations et services.',
      meta: ['2025', 'Duo', 'Java · POO'],
      boss: {
        name: 'Overbooking',
        sprite: 'bell',
        desc: 'Deux clients, une chambre, zéro règle métier.',
      },
      intro:
        "Projet d'école en binôme : modéliser un hôtel en programmation orientée objet, de la chambre à la facture. J'ai pris en charge le flux de réservation côté client et la logique des services.",
      hits: [
        { name: 'Classe abstraite', desc: 'Chambre fixe le contrat ; Simple, Double et Suite le précisent.' },
        { name: 'Polymorphisme', desc: 'Chaque type de chambre calcule son prix, la Suite (jacuzzi, balcon) surcharge le calcul.' },
        { name: 'java.time', desc: 'Nombre de nuits calculé à partir des dates, sans bricolage.' },
        { name: 'Services à la carte', desc: 'Petit-déjeuner, spa… ajoutés à la réservation et facturés.' },
        { name: 'Recherche filtrée', desc: 'Chambres par numéro, par type ou sous un budget maximum.' },
      ],
      super: {
        name: 'Facture totale',
        desc: 'Chambre + services : le prix final se calcule tout seul, réservation par réservation.',
      },
      results: [
        { value: '9', label: 'classes Java' },
        { value: '3', label: 'types de chambre' },
        { value: '2', label: 'développeurs' },
      ],
      stack: ['Java', 'POO', 'java.time', 'Collections', 'Eclipse', 'Git'],
      note: 'Code d’origine privé (projet à deux). La démo reprend le modèle objet et ses prix.',
      access: [{ label: 'Réserver une chambre', href: 'demos/hotel/', kind: 'demo' }],
      perks: ['Java', 'POO'],
    },
    {
      id: 'trone',
      crew: 'À trois',
      tile: 'ProjecTTrone',
      name: 'ProjecTTrone',
      kicker: 'Projet à trois · 2023',
      tagline: 'Jeu d’action 3D développé à trois, d’Unreal Engine à Unity.',
      meta: ['2023', 'Trio', 'Unity · C# · Unreal'],
      boss: {
        name: 'Le moteur 3D',
        sprite: 'cube',
        desc: 'Physique, caméras, collisions : un monde entier à dompter.',
      },
      intro:
        'Mon premier gros projet d’équipe : une ville médiévale en 3D à explorer, des objets et des armes à ramasser. Une V1 sous Unreal Engine, puis une V2 sous Unity. J’ai codé les menus, l’inventaire et le ramassage, et géré les fusions de branches.',
      hits: [
        { name: 'V1 · Unreal Engine', desc: 'Premier prototype en C++ et Blueprints.' },
        { name: 'V2 · Unity 2022', desc: 'Reprise en C# pour itérer plus vite.' },
        { name: 'Caméra 3e personne', desc: 'Contrôleur de personnage et caméra qui suit le joueur.' },
        { name: 'Inventaire', desc: 'Objets et données séparés (Item / ItemData), panneau ouvert avec la touche I.' },
        { name: 'Ramassage', desc: 'Détection par raycast : « Press E » dès qu’un objet est à portée.' },
        { name: 'Git en équipe', desc: 'Une branche par fonctionnalité (menu, carte, objets), puis fusion.' },
      ],
      super: {
        name: 'Ville médiévale',
        desc: 'Personnage, carte et objets réunis dans une même scène jouable.',
      },
      results: [
        { value: '3', label: 'développeurs' },
        { value: '2', label: 'moteurs de jeu' },
        { value: '3', label: 'scènes (menu, ville, bac à sable)' },
      ],
      stack: ['Unity', 'C#', 'Unreal Engine', 'C++', 'Blueprints', 'Git'],
      note: 'Code d’origine privé (assets sous licence). La démo recrée en 2D le ramassage et l’inventaire.',
      access: [{ label: 'ProjecTTrone Lite (mini-jeu)', href: 'demos/projecttrone/', kind: 'demo' }],
      perks: ['Unity', 'C#', 'Travail en équipe'],
    },
    {
      id: 'portfolio',
      crew: 'Solo',
      tile: 'Portfolio',
      name: 'Ce portfolio',
      kicker: 'Projet solo · 2026',
      tagline: 'Un portfolio jouable, fait main, sans framework.',
      meta: ['2026', 'Solo', 'HTML · CSS · JS'],
      boss: {
        name: 'Le CV ennuyeux',
        sprite: 'paper',
        desc: 'Une page, des puces, et personne ne lit jusqu’au bout.',
      },
      intro:
        'Plutôt qu’un CV de plus, une borne d’arcade : chaque projet est une mission contre un problème, chaque compétence une manipulation, chaque diplôme une amélioration. Tout est fait main et reste lisible sans JavaScript.',
      hits: [
        { name: 'Zéro framework', desc: 'HTML, CSS et JavaScript natifs, en modules ES.' },
        { name: 'Build maison', desc: 'Un générateur Node sans dépendance produit les pages FR et EN.' },
        { name: 'Pixel art en SVG', desc: 'Sprites dessinés par code, rendus en SVG net à n’importe quelle taille.' },
        { name: 'Buffer d’entrées', desc: 'Détection des manipulations façon jeu de combat (236P, 623K…), clavier AZERTY ou QWERTY.' },
        { name: 'Manette', desc: 'Gamepad API : branche ta manette ou ton stick arcade.' },
        { name: 'Sécurité', desc: 'Politique CSP stricte, aucune ressource externe, CI avec analyse CodeQL.' },
      ],
      super: {
        name: 'Mode lecture',
        desc: 'Une version sobre et accessible, sans animation, à un clic.',
      },
      results: [
        { value: '0', label: 'dépendance à l’exécution' },
        { value: '2', label: 'langues' },
        { value: '6', label: 'démos jouables, une par projet' },
      ],
      stack: ['HTML', 'CSS', 'JavaScript', 'Node.js', 'SVG', 'Web Audio', 'Gamepad API', 'GitHub Actions', 'CodeQL', 'GitHub Pages'],
      note: '',
      access: [{ label: 'Code source', href: 'https://github.com/MrgMF/MRGMF.github.io', kind: 'code' }],
      perks: ['Web natif', 'Accessibilité', 'CSP'],
    },
    {
      id: 'archives',
      secret: true,
      crew: 'Solo',
      tile: 'Archives',
      name: 'Archives',
      kicker: 'Mission secrète · 2023 – 2025',
      tagline: 'Les premiers rounds.',
      meta: ['2023 – 2025', 'Débuts', 'HTML · PHP · React'],
      boss: {
        name: 'La disquette',
        sprite: 'floppy',
        desc: 'Elle garde tout. Même les premiers essais.',
      },
      intro: 'Mission débloquée ! Voici les projets d’avant : pas parfaits, mais c’est là que tout a commencé.',
      hits: [
        { name: 'ArtisteCity · 2023', desc: 'Réseau social pour artistes : galerie, écoute de morceaux, envoi de fichiers (HTML, CSS, PHP).' },
        { name: 'Mise en relation · 2025', desc: 'Maquette interactive élèves / professeurs : profils, messagerie, réglages (React, TypeScript, prototypée avec Figma Make).' },
      ],
      super: {
        name: 'Premier site',
        desc: 'Un CV en HTML publié sur GitHub Pages. Ce portfolio a pris sa place.',
      },
      results: [
        { value: '2021', label: 'premier compte GitHub' },
        { value: '2023', label: 'premiers projets en ligne' },
      ],
      stack: ['HTML', 'CSS', 'PHP', 'React', 'TypeScript', 'Figma'],
      note: '',
      access: [],
      perks: [],
    },
  ],

  // Diplômes et certifications : les « améliorations » du joueur 1.
  upgrades: [
    { id: 'bac', icon: 'scroll', kind: 'Diplôme', name: 'Bac STI2D', org: 'Sciences et technologies de l’industrie et du développement durable', date: '2020', perks: ['Électronique', 'Systèmes'] },
    { id: 'licence', icon: 'scroll', kind: 'Formation', name: 'Licence Mathématiques-Informatique', org: 'Université d’Évry', date: '2020 – 2022', perks: ['Mathématiques', 'Algorithmique'] },
    { id: 'bts', icon: 'scroll', kind: 'Diplôme', name: 'BTS CIEL', org: 'Cybersécurité, informatique et réseaux · en alternance', date: '2023 – 2025', perks: ['Réseaux', 'Cybersécurité'] },
    { id: 'cisco', icon: 'medal', kind: 'Certification', name: 'Junior Cybersecurity Analyst', org: 'Cisco · parcours certifiant', date: 'Mars 2025', perks: ['Analyse de sécurité'] },
    {
      id: 'lvmh',
      icon: 'medal',
      kind: 'Certifications',
      name: 'LVMH Fast Tracks',
      org: 'LVMH · 6 certificats',
      date: 'Juillet – août 2025',
      perks: ['Data', 'IA générative', 'Éthique & conformité'],
      list: ['Data Fast Track', 'Cybersecurity Fast Track', 'Generative AI Fast Track', 'Green in Tech Fast Track', 'Clienteling Fast Track', 'Ethics & Compliance Certificate'],
    },
    {
      id: 'nxt',
      icon: 'medal',
      kind: 'Certifications',
      name: 'Certified Nexthink Associate',
      org: 'Nexthink · 2 certifications',
      date: 'Janvier 2026',
      perks: ['Nexthink', 'DEX'],
      list: ['Certified Nexthink Associate', 'Certified Nexthink Associate in IT Support'],
    },
    { id: 'bachelor', icon: 'cap', kind: 'Diplôme', name: 'Bachelor Concepteur Développeur d’Applications', org: 'ECE Paris · en alternance', date: '2025 – 2026', perks: ['Conception', 'Architecture en couches'] },
    { id: 'rncp', icon: 'medal', kind: 'Titre', name: 'Titre RNCP niveau 6 validé', org: 'Concepteur Développeur d’Applications', date: '2026', perks: ['Tests & DevOps', 'Sécurité applicative'] },
    { id: 'ece', icon: 'cap', kind: 'Diplôme en cours', name: 'Cycle ingénieur · Data & IA', org: 'ECE Paris · en alternance chez Louis Vuitton', date: '2026 – 2029', perks: ['Data', 'IA'], status: 'En cours' },
    { id: 'next', icon: 'lock', kind: '???', name: 'Prochaine amélioration', org: 'À débloquer', date: '…', perks: [], locked: true },
  ],

  // Les entreprises ne sont pas des adversaires : ce sont les équipes du
  // joueur 1. Nexthink est un allié « assist » appelé en renfort.
  teams: {
    heading: 'Équipes & alliés',
    intro: 'Les entreprises ne sont pas des adversaires : ce sont les équipes aux côtés desquelles j’affronte les problèmes.',
    team: 'Équipe',
    ally: 'Allié',
    missions: 'Missions',
    list: [
      {
        id: 'lv',
        kind: 'team',
        name: 'Louis Vuitton',
        role: 'End User Architect · alternance',
        date: 'Depuis 2025',
        desc: 'Équipe Digital Workplace : Microsoft 365, gouvernance des identités et expérience numérique des collaborateurs.',
      },
      {
        id: 'bain',
        kind: 'team',
        name: 'Bain & Company',
        role: 'Assistant IT · alternance',
        date: '2023 – 2025',
        desc: 'Support IT du niveau 1 au niveau 3, avec des équipes IT locales et internationales.',
      },
      {
        id: 'nexthink',
        kind: 'ally',
        sprite: 'drone',
        name: 'Nexthink',
        role: 'Assist · plateforme DEX',
        date: 'Certifié ×2 (2026)',
        desc: 'Surveille le parc, repère les postes qui dérivent et corrige à distance. Appelé en renfort dans la mission Expérience numérique.',
      },
    ],
  },

  // Mode arcade : l'ordre du parcours, boss et améliorations mêlés.
  ladder: ['bac', 'licence', 'trone', 'bts', 'bain', 'cisco', 'lv', 'lvmh', 'nxt', 'nexthink', 'bachelor', 'hotel', 'learnlink', 'rncp', 'ece', 'portfolio', 'next'],

  progress: {
    kicker: 'Mode arcade',
    heading: 'Progression',
    intro:
      'Mon parcours façon mode arcade : les boss sont les problèmes affrontés en mission, les améliorations mes diplômes et certifications. Chaque étape franchie fait monter le joueur 1 d’un niveau.',
    start: 'Lancer l’arcade',
    resume: 'Reprendre l’arcade',
    restart: 'Recommencer',
    level: 'Niveau',
    steps: 'étapes franchies',
    ladderLabel: 'Étapes du parcours',
    boss: 'Mission',
    against: 'contre',
    upgrade: 'Amélioration',
    cleared: 'Vaincu',
    obtained: 'Obtenu',
    inProgress: 'En cours',
    locked: 'À débloquer',
    fight: 'Combattre',
    see: 'Voir',
  },

  upgradeScreen: {
    banner: 'Amélioration !',
    perksTitle: 'Nouvelles compétences',
    levelUp: 'Niveau',
    continue: 'Continuer',
    toProgress: 'Voir la progression',
    certs: 'Certificats inclus',
    lockedBanner: 'À suivre…',
    lockedText: 'La prochaine amélioration s’écrit en ce moment. Et la prochaine mission, peut-être avec toi.',
    toContact: 'Proposer une mission',
  },

  moves: {
    kicker: 'Move list',
    heading: 'Compétences',
    demo: 'Voir la manipulation',
    intro:
      'Mes compétences, en manipulations. Exécute-les au clavier (flèches ou ZQSD + J/K) ou à la manette : chaque coup réussi s’illumine.',
    legend: [
      ['P', 'Poing : J'],
      ['K', 'Pied : K'],
      ['6', 'Avant'],
      ['2', 'Bas'],
    ],
    progress: 'manipulations réussies',
    tapHint: 'Sur mobile : touche un coup pour voir la manipulation.',
    allFound: 'Move list complète ! Adversaire secret débloqué.',
    groups: [
      {
        title: 'Spéciaux · Gouvernance & accès',
        moves: [
          { id: 'ca', name: 'Accès conditionnel', input: '236P', desc: 'Stratégies Microsoft Entra ID : MFA, comptes invités, conditions d’accès, déploiement progressif.' },
          { id: 'rbac', name: 'Garde RBAC', input: '41236K', desc: 'Rôles, groupes et droits : moindre privilège dans Active Directory, Entra ID et les applications.' },
          { id: 'runbook', name: 'Demande d’accès', input: '623K', desc: 'Circuit de demande en self-service (Power Apps) exécuté par Azure Automation.' },
          { id: 'mfa', name: 'Double facteur', input: '214P', desc: 'MFA, TOTP (RFC 6238), OAuth 2.0 et OpenID Connect.' },
        ],
      },
      {
        title: 'Spéciaux · Microsoft 365 & automatisation',
        moves: [
          { id: 'm365', name: 'Combo M365', input: '41236P', desc: 'Exchange Online, Teams, SharePoint : comptes, accès et collaboration externe.' },
          { id: 'ps', name: 'Rafale PowerShell', input: '236K', desc: 'Scripts, API REST, rapports et tâches planifiées.' },
          { id: 'graph', name: 'Appel Graph', input: '63214P', desc: 'Microsoft Graph API : utilisateurs, groupes, e-mails.' },
          { id: 'vault', name: 'Coffre-fort', input: '22P', desc: 'Azure Key Vault : les secrets restent hors du code.' },
          { id: 'flow', name: 'Flow', input: '214K', desc: 'Power Automate pour les processus du quotidien.' },
        ],
      },
      {
        title: 'Spéciaux · Poste de travail',
        moves: [
          { id: 'nexthink', name: 'Scan Nexthink', input: '623P', desc: 'Requêtes NQL, Remote Actions, campagnes et score DEX.' },
          { id: 'ticket', name: 'Ticket Rush', input: '66P', desc: 'Support de N1 à N3 et incidents dans ServiceNow (Bain & Company).' },
        ],
      },
    ],
    super: { id: 'zt', name: 'Zero Trust', input: '236236PK', desc: 'Ne jamais faire confiance, toujours vérifier : gouvernance, contrôle d’accès et supervision réunis.' },
    superTitle: 'Super',
    normalsTitle: 'Normaux · Dév & DevOps',
    normals: ['JavaScript', 'Node.js', 'Express', 'React', 'MongoDB', 'PostgreSQL', 'Java', 'C#', 'Python', 'Docker', 'GitHub Actions', 'Prometheus', 'Grafana', 'Jest', 'Git'],
  },

  profile: {
    heading: 'Fiche combattant',
    name: 'Fodié Marega',
    tag: 'MRGMF',
    rows: [
      ['Classe', 'End User Architect (alternance chez Louis Vuitton)'],
      ['Équipes', 'Louis Vuitton (depuis 2025) · Bain & Company (2023 – 2025)'],
      ['Allié', 'Nexthink (certifié ×2)'],
      ['Spécialité', 'IAM : gouvernance et architecture des identités'],
      ['Style', 'Moindre privilège · Accès conditionnel · Automatisation'],
      ['Arme favorite', 'PowerShell'],
      ['Coup signature', 'Accès conditionnel (236P)'],
      ['Point faible', 'Les mots de passe tout seuls'],
      ['Hors du ring', 'Jeux de combat (FGC) et jeux de cartes à collectionner'],
    ],
    bio: 'Mon terrain : la gouvernance et l’architecture des identités. Définir qui accède à quoi et à quelles conditions, puis le rendre vérifiable et automatisé, du tenant Microsoft 365 jusqu’au code des applications.',
    quoteLabel: 'Phrase de victoire',
    quote: '« Un accès, ça se mérite. Et ça se vérifie. »',
    costume: 'Couleur',
    costumes: ['Bleu P1', 'Rouge P2', 'Vert néon', 'Or', 'Ombre'],
  },

  contact: {
    banner: 'Challenger en approche !',
    heading: 'Contact',
    text: 'Un projet, une question sur la gouvernance des identités ou l’automatisation, ou juste envie d’une revanche ? Écris-moi.',
    email: { user: 'fodiemarega91', domain: 'gmail.com' },
    emailLabel: 'Envoyer un e-mail',
    copy: 'Copier l’adresse',
    copied: 'Adresse copiée !',
    copyFail: 'Copie impossible : l’adresse est affichée à l’écran.',
    linkedin: 'https://www.linkedin.com/in/fodi%C3%A9marega/',
    github: 'https://github.com/MrgMF',
    continue: 'Continue ?',
    gameOver: 'Game over ? Pas si tu m’écris.',
  },

  notFound: {
    heading: 'Game over',
    text: 'Cette page n’existe pas (ou plus). Il te reste un crédit.',
    continue: 'Continue ?',
    cta: 'Retour à l’écran titre',
  },

  konami: 'Code accepté !',
};
